const assert=require('node:assert/strict'),path=require('node:path'),esbuild=require('../node_modules/.pnpm/node_modules/esbuild');
(async()=>{const out=path.resolve('.sites-runtime/pricing-table-logic.cjs');await esbuild.build({entryPoints:['lib/studio-settings.ts'],outfile:out,bundle:true,format:'cjs',platform:'node',logLevel:'error'});const {defaultServices,serviceEstimate,rateService,pricingMode}=require(out),services=defaultServices(),find=id=>services.find(s=>s.id===id);
assert.equal(serviceEstimate(find('hour'),3,{}),180);assert.equal(serviceEstimate(find('render'),5,{}),550);assert.equal(serviceEstimate(find('model'),60,{}),330);assert.equal(serviceEstimate(find('model'),10,{}),300);assert.equal(serviceEstimate(find('plan'),3,{}),750);assert.equal(serviceEstimate(find('interiors'),60,{}),2400);assert.equal(serviceEstimate(find('technical'),60,{}),760);
const packs={...find('render'),packages:[{quantity:5,value:550},{quantity:10,value:1000}]};assert.equal(serviceEstimate(packs,12,{}),1240);assert.equal(serviceEstimate(packs,10,{}),1000);assert.equal(serviceEstimate({...packs,packages:[]},5,{}),600);
const fixed={...find('custom'),mode:'fixed',value:1200};assert.equal(serviceEstimate(fixed,8,{}),1200);assert.equal(serviceEstimate(fixed,1,{}, {closedValue:980}),980);
const multi={...find('model'),alternatives:[{mode:'hour',value:60,fixed:0,minimum:0}]};assert.equal(serviceEstimate(rateService(multi,0),3,{}),180);assert.equal(pricingMode({unit:'m²',packageQuantity:0}),'area');
const flowOut=path.resolve('.sites-runtime/pricing-table-flow.cjs');await esbuild.build({entryPoints:['lib/studio-flow.ts'],outfile:flowOut,bundle:true,format:'cjs',platform:'node',logLevel:'error'});const {buildBudgetIntegration}=require(flowOut),client={id:'client',kind:'clients',title:'Teste'},item={id:'item',title:'Render',quantity:5,unitValue:110,pricingSnapshot:structuredClone(find('render'))},budget={id:'quote',kind:'budgets',title:'Apartamento',client:'client',items:[item],installments:2,discount:50,paymentScheduleMode:'Parcelas mensais'};
find('render').value=999;assert.equal(item.pricingSnapshot.value,120);const flow=buildBudgetIntegration(budget,[client],'2026-10-03');assert.equal(flow.generated.find(r=>r.kind==='projects').value,500);assert.equal(flow.generated.find(r=>r.kind==='contracts').value,500);assert.equal(flow.generated.filter(r=>r.kind==='finance').reduce((n,r)=>n+r.value,0),500);
console.log('PASS: reference amounts, minimums, multi-package optimization, fixed/alternative pricing, preserved snapshot and approved-budget totals in demand, contract and finance.');})().catch(e=>{console.error(e);process.exit(1)});
