// Integration tests run against real SQLite in memory; never use the production database.
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {DatabaseSync}=require('node:sqlite');
const esbuild=require('../node_modules/.pnpm/node_modules/esbuild');
const sql=new DatabaseSync(':memory:');
for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+file,'utf8'));
class Statement{
 constructor(query,args=[]){this.query=query;this.args=args;}
 bind(...args){return new Statement(this.query,args)}
 async first(){return sql.prepare(this.query).get(...this.args)||null}
 async all(){return {results:sql.prepare(this.query).all(...this.args)}}
 runSync(){const r=sql.prepare(this.query).run(...this.args);return {meta:{changes:Number(r.changes)}}}
}
globalThis.__lnTestDB={prepare:q=>new Statement(q),batch:async statements=>{sql.exec('BEGIN');try{const result=statements.map(s=>s.runSync());sql.exec('COMMIT');return result}catch(e){sql.exec('ROLLBACK');throw e}}};
async function compile(entry,name){const file=path.resolve('.sites-runtime/'+name+'.cjs');await esbuild.build({entryPoints:[entry],bundle:true,format:'cjs',platform:'node',outfile:file,alias:{'@/lib/store':path.resolve('tests/d1-test-store.ts')},tsconfig:'tsconfig.json',logLevel:'error'});return require(file)}
async function main(){const api=await compile('app/api/records/route.ts','test-records');const audit=await compile('app/api/history/route.ts','test-history');async function post(record){const r=await api.POST(new Request('http://test/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(record)}));return {status:r.status,body:await r.json()}}
 const client={id:'client-one',kind:'clients',title:'Cliente teste',email:'teste@example.com',city:'Mogi das Cruzes',state:'SP'};
 const created=await post(client);assert.equal(created.status,200);assert.equal(created.body.record.revision,1);
 const updated=await post({...created.body.record,title:'Cliente editado'});assert.equal(updated.status,200);assert.equal(updated.body.record.revision,2);
 assert.equal((await post({...created.body.record,title:'Overwrite stale'})).status,409);
 assert.equal((await post({...updated.body.record,email:'invalid'})).status,400);
 assert.equal((await post({id:'invalid',kind:'clients',title:''})).status,400);
 const project=await post({id:'project-one',kind:'projects',title:'Apartamento',client:client.id,startDate:'2026-10-02',deadline:'2026-10-30',stages:[{id:'stage-one',title:'Layout',status:'Em andamento'}]});assert.equal(project.status,200);
 assert.equal((await post({id:'bad-project',kind:'projects',title:'Inválido',client:'missing'})).status,400);
 assert.equal((await post({id:'bad-date',kind:'projects',title:'Inválido',startDate:'2026-10-10',deadline:'2026-10-02'})).status,400);
 assert.equal((await post({id:'bad-calendar',kind:'projects',title:'Inválido',deadline:'2026-02-31'})).status,400);
 const finance=await post({id:'finance-one',kind:'finance',title:'Parcela',project:'project-one',value:2800,type:'Receita',status:'Pendente'});assert.equal(finance.status,200);assert.equal(finance.body.record.client,'client-one');
 const deleted=await post({...updated.body.record,deleted:true});assert.equal(deleted.status,200);
 const newLink=await post({id:'new-after-delete',kind:'budgets',title:'Proposta',client:'client-one'});assert.equal(newLink.status,400);
 const restored=await post({...deleted.body.record,deleted:false});assert.equal(restored.status,200);
 const records=await (await api.GET()).json();assert.equal(records.records.filter(r=>r.id==='client-one').length,1);assert.equal(records.records.find(r=>r.id==='client-one').deleted,false);
 const history=await (await audit.GET(new Request('http://test/api/history?id=client-one'))).json();assert.equal(history.history.length,6);assert(history.history.some(r=>r.action==='excluído'));assert(history.history.some(r=>r.action==='restaurado'));assert(history.history.some(r=>r.recordId==='project-one'));assert(history.history.some(r=>r.recordId==='finance-one'));
 const projectDeleted=await post({...project.body.record,deleted:true});assert.equal(projectDeleted.status,200);const afterDelete=await (await api.GET()).json();assert(afterDelete.records.some(r=>r.id==='finance-one'));assert.equal((await post({...projectDeleted.body.record,deleted:false})).status,200);
 const versions=await compile('app/api/versions/route.ts','test-versions');const savedVersions=await (await versions.GET(new Request('http://test/api/versions?id=client-one'))).json();assert.equal(savedVersions.versions.length,4);assert(savedVersions.versions.every(v=>v.record.id==='client-one'));
 const integrate=await compile('app/api/integrate/route.ts','test-integrate');async function call(route,data){const r=await route.POST(new Request('http://test/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}));return {status:r.status,body:await r.json()};}
 const budget=await post({id:'budget-integration',kind:'budgets',title:'Proposta completa',audience:'Freelancer',deliveryFormats:'PDF e SKP conforme combinado',client:'client-one',status:'Aprovado',items:[{id:'service',title:'Interiores',quantity:1,unitValue:100}],discount:0,installments:3,firstDue:'2026-01-31',deadline:'2026-11-30'});assert.equal(budget.status,200);const integrated=await call(integrate,{budgetId:'budget-integration'});assert.equal(integrated.status,200);const once=await (await api.GET()).json();const generated=once.records.filter(r=>r.budget==='budget-integration');assert.equal(generated.filter(r=>r.kind==='contracts').length,1);for(const r of generated.filter(r=>['contracts','projects'].includes(r.kind))){assert.equal(r.audience,'Freelancer');assert.equal(r.deliveryFormats,'PDF e SKP conforme combinado');}assert.equal(generated.filter(r=>r.kind==='tasks').length,6);assert.equal(generated.filter(r=>r.kind==='finance').length,3);assert.equal(generated.filter(r=>r.kind==='finance').reduce((a,r)=>a+Math.round(r.value*100),0),10000);assert.equal((await call(integrate,{budgetId:'budget-integration'})).body.reused,true);const twice=await (await api.GET()).json();assert.equal(twice.records.length,once.records.length);
 const refused=await post({id:'unapproved-budget',kind:'budgets',title:'Não aprovada',client:'client-one',status:'Rascunho'});assert.equal((await call(integrate,{budgetId:refused.body.record.id})).status,400);
 const splits=await compile('app/api/installments/route.ts','test-split');const manual=await post({id:'manual-finance',kind:'finance',title:'Receita parcelada',value:10,date:'2026-01-31',installments:3,status:'Pendente',type:'Receita'});assert.equal(manual.status,200);assert.equal((await call(splits,{id:'manual-finance'})).status,200);assert.equal((await call(splits,{id:'manual-finance'})).body.reused,true);const splitRows=(await (await api.GET()).json()).records.filter(r=>r.id.startsWith('manual-finance'));assert.equal(splitRows.length,3);assert.equal(splitRows.reduce((a,r)=>a+Math.round(r.value*100),0),1000);
 const processes=await compile('lib/work-processes.ts','test-integrated-processes');const model=processes.defaultProcesses().find(p=>p.id==='freela');const modeled=await post({id:'budget-process',kind:'budgets',title:'Proposta com processo',client:'client-one',status:'Aprovado',audience:'Freelancer',value:100,startDate:'2026-10-02',processSnapshot:model});assert.equal(modeled.status,200);assert.equal((await call(integrate,{budgetId:'budget-process'})).status,200);const allModeled=(await (await api.GET()).json()).records.filter(r=>r.budget==='budget-process'||r.id==='gen-budget-process-project');const modeledProject=allModeled.find(r=>r.kind==='projects');assert.equal(modeledProject.stages.length,3);assert.equal(modeledProject.stages[0].deadline,'2026-10-06');assert.equal(allModeled.filter(r=>r.kind==='finance').length,2);assert.equal(allModeled.filter(r=>r.kind==='finance').reduce((a,r)=>a+Math.round(r.value*100),0),10000);assert.equal(allModeled.filter(r=>r.kind==='agenda').length,3);assert.equal(allModeled.find(r=>r.kind==='contracts').processSnapshot.id,'freela');model.steps[0].title='Changed later';assert.notEqual(modeledProject.processSnapshot.steps[0].title,model.steps[0].title);console.log('PASS: process snapshot creates dated project stages, stage payments, deadlines and contract without later template changes.');
 const demandPay=await compile('lib/demand-payments.ts','test-linked-demand-payments');const newPay={...demandPay.newDemandPayment(modeledProject,'2026-10-02'),title:'Parcela adicional acordada',value:25};const savedPay=await post(newPay);assert.equal(savedPay.status,200);const paidPay=await post(demandPay.paidDemandPayment(savedPay.body.record,true,'2026-10-02'));assert.equal(paidPay.status,200);const savedFinance=(await (await api.GET()).json()).records;assert.equal(savedFinance.filter(r=>r.id===newPay.id).length,1);assert.equal(savedFinance.find(r=>r.id===newPay.id).status,'Pago');assert.equal(savedFinance.find(r=>r.id===newPay.id).project,modeledProject.id);assert.equal(demandPay.paymentSummary(modeledProject,savedFinance).paid,25);console.log('PASS: payment added from demand persists as one linked finance record and paid state is reloaded by both views.');
 const linkedClient=await post({id:'client-auto',kind:'clients',title:'Bia',profession:'Arquiteta(o)',clientType:'Freelancer',projectName:'Apartamento 53',value:2000,dealStatus:'Orçamento',installments:4});assert.equal(linkedClient.status,200);assert.equal(linkedClient.body.records.filter(r=>r.kind==='budgets'&&r.client==='client-auto').length,1);const autoProposal=linkedClient.body.records.find(r=>r.kind==='budgets'&&r.client==='client-auto');const autoClosed=await post({...autoProposal,status:'Aprovado'});assert.equal(autoClosed.status,200);assert(autoClosed.body.record.integration.completed);assert.equal(autoClosed.body.records.filter(r=>r.kind==='finance'&&r.client==='client-auto').length,4);const sync=await compile('app/api/reconcile/route.ts','test-reconcile');const synchronized=await sync.POST();assert.equal(synchronized.status,200);const again=await sync.POST();assert.equal(again.status,200);assert.equal((await again.json()).count,0);const atomicBefore=(await (await api.GET()).json()).records.length;const originalBatch=globalThis.__lnTestDB.batch;globalThis.__lnTestDB.batch=async statements=>originalBatch([...statements,new Statement('INSERT INTO missing_table VALUES (1)')]);const originalLog=console.error;console.error=()=>{};const failedClose=await post({id:'atomic-auto-client',kind:'clients',title:'Cliente atomic',projectName:'Novo projeto',value:500,dealStatus:'Pedido fechado'});console.error=originalLog;globalThis.__lnTestDB.batch=originalBatch;assert.equal(failedClose.status,503);assert.equal((await (await api.GET()).json()).records.length,atomicBefore);console.log('PASS: client creates proposal, closing creates monthly installments automatically, reconciliation is idempotent and failed automatic flow rolls back all records.');
 // Inject a failing statement to verify the integration transaction rolls back completely.
 const rollback=await post({id:'rollback-budget',kind:'budgets',title:'Rollback',client:'client-one',status:'Rascunho',value:90,installments:3});sql.prepare('UPDATE records SET payload=? WHERE id=?').run(JSON.stringify({...rollback.body.record,status:'Aprovado'}),'rollback-budget');const realBatch=globalThis.__lnTestDB.batch;globalThis.__lnTestDB.batch=async statements=>realBatch([...statements,new Statement('INSERT INTO missing_table VALUES (1)')]);const logged=console.error;console.error=()=>{};const fail=await call(integrate,{budgetId:rollback.body.record.id});console.error=logged;globalThis.__lnTestDB.batch=realBatch;assert.equal(fail.status,503);const rolled=(await (await api.GET()).json()).records;assert(!rolled.some(r=>r.id==='gen-rollback-budget-project'));assert(!rolled.find(r=>r.id==='rollback-budget').integration);
 console.log('PASS: versions, idempotent approved-budget integration, finance splitting and transactional rollback.');
 console.log('PASS: create/edit/read, revisions, invalid input, dates, linked data, audit history, trash/restore and preservation of linked finance.');
 sql.close();}
main().catch(e=>{console.error(e);process.exit(1)});
