import {recordArchived,clientInHistory} from './work-archive';
import {Entry} from './studio-types';
import {financeSituation} from './work-processes';
import {complete,localDay} from './operations-data';
import {clientSummary} from './operations-data';
export function clientPanelData(client:Entry,rows:Entry[]){const summary=clientSummary(client,rows),budgets=rows.filter(r=>r.kind==='budgets'&&!r.deleted&&r.client===client.id).sort((a,b)=>(b.date||'').localeCompare(a.date||'')),closed=(r:Entry)=>!!client.archived||!!r.integration?.completed||['Aprovado','Pedido fechado','Recusado'].includes(r.status)||!!r.archived;return {...summary,projects:rows.filter(r=>r.kind==='projects'&&!r.deleted&&r.client===client.id),budgets,openBudgets:budgets.filter(r=>!closed(r)),historyBudgets:budgets.filter(closed)};}
export function panelGroups(rows:Entry[]){const clients=rows.filter(r=>r.kind==='clients'&&!r.deleted);return {open:clients.filter(c=>clientPanelData(c,rows).openBudgets.length>0),history:clients.filter(c=>{const d=clientPanelData(c,rows);return !d.openBudgets.length&&(d.budgets.length>0||d.projects.length>0)}),other:clients.filter(c=>{const d=clientPanelData(c,rows);return !d.budgets.length&&!d.projects.length})};}
/** Group work, rather than whole clients: one client may have projects in all three states. */
export function clientWorkGroups(rows:Entry[]){const clients=rows.filter(r=>r.kind==='clients'&&!r.deleted),projects=rows.filter(r=>r.kind==='projects'&&!r.deleted),budgets=rows.filter(r=>r.kind==='budgets'&&!r.deleted),groups:{execution:any[];completed:any[];quotes:any[];other:Entry[]}={execution:[],completed:[],quotes:[],other:[]};for(const client of clients){const own=projects.filter(p=>p.client===client.id),quotes=budgets.filter(b=>b.client===client.id);for(const p of own){const finance=rows.filter(r=>r.kind==='finance'&&!r.deleted&&!r.archived&&r.type==='Receita'&&r.scope!=='personal'&&(r.project===p.id||r.client===client.id&&!r.project&&own.length===1));const stats={paid:finance.filter(r=>r.status==='Pago').reduce((n,r)=>n+Number(r.value||0),0),pending:finance.filter(r=>r.status!=='Pago').reduce((n,r)=>n+Number(r.value||0),0),overdue:finance.filter(r=>financeSituation(r,localDay())==='Atrasado').reduce((n,r)=>n+Number(r.value||0),0)};const item={id:'project-'+p.id,client,record:p,stats};groups[recordArchived(p,rows)?'completed':'execution'].push(item)}for(const b of quotes){const linked=own.find(p=>p.id===b.project||p.budget===b.id);if(linked&&['Aprovado','Pedido fechado'].includes(b.status)||linked&&b.integration?.completed)continue;const closed=['Aprovado','Pedido fechado'].includes(b.status)||b.integration?.completed;const item={id:'quote-'+b.id,client,record:b,stats:{paid:0,pending:0,overdue:0}};groups[recordArchived(b,rows)?'completed':closed?'execution':'quotes'].push(item)}if(!own.length&&!quotes.length&&!clientInHistory(client,rows))groups.other.push(client)}return groups;}
