import {Entry} from './studio-types';
export const workflowStages=['Em alinhamento','Em execução','Em ajustes','Em aprovação','Entregue'];
export const complete=(r:Entry)=>['Concluído','Entregue'].includes(r.status)||r.workflowStatus==='Entregue';
export const localDay=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'});
export const dateKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export function workflow(r:Entry){if(complete(r))return 'Entregue';if(workflowStages.includes(r.workflowStatus||r.status))return r.workflowStatus||r.status;return ({'A fazer':'Em alinhamento',Briefing:'Em alinhamento','Em andamento':'Em execução',Layout:'Em execução',Modelagem:'Em execução',Apresentação:'Em aprovação',Detalhamento:'Em execução'} as Record<string,string>)[r.status]||'Em alinhamento';}
export function deadlineLabel(r:Entry,today=localDay()){if(!r.deadline)return 'Sem prazo';if(complete(r))return 'Entregue';const delta=Math.round((Date.parse(r.deadline+'T12:00:00')-Date.parse(today+'T12:00:00'))/86400000);return delta<0?`Atrasado ${-delta} dia(s)`:delta===0?'Entrega hoje':delta===1?'Entrega amanhã':`Faltam ${delta} dias`;}
export function clientSummary(client:Entry,rows:Entry[]){const related=rows.filter(r=>!r.deleted&&!r.archived&&(r.client===client.id||r.kind==='tasks'&&rows.some(p=>p.id===r.project&&p.client===client.id)));const projects=related.filter(r=>r.kind==='projects'),finance=related.filter(r=>r.kind==='finance'&&r.type==='Receita');const paid=finance.filter(r=>r.status==='Pago').reduce((a,r)=>a+Number(r.value||0),0),total=finance.reduce((a,r)=>a+Number(r.value||0),0)||projects.reduce((a,r)=>a+Number(r.value||0),0);return {related,projects,paid,total,pending:finance.filter(r=>r.status!=='Pago').reduce((a,r)=>a+Number(r.value||0),0),unsigned:related.filter(r=>r.kind==='contracts'&&r.status!=='Assinado'),deadline:projects.filter(p=>!complete(p)&&p.deadline).map(p=>p.deadline).sort()[0]||'',current:projects.find(p=>!complete(p))};}
export function financePeriod(rows:Entry[],month:string){const finance=rows.filter(r=>r.kind==='finance'&&!r.deleted&&!r.archived);const receipts=finance.filter(r=>r.type==='Receita'&&r.status==='Pago'&&(r.paidDate||r.date||'').startsWith(month));const expenses=finance.filter(r=>r.type==='Despesa'&&(r.date||'').startsWith(month));const received=receipts.reduce((a,r)=>a+Number(r.value||0),0),spent=finance.filter(r=>r.type==='Despesa'&&r.status==='Pago'&&(r.paidDate||r.date||'').startsWith(month)).reduce((a,r)=>a+Number(r.value||0),0);return {received,expected:finance.filter(r=>r.type==='Receita'&&r.status!=='Pago'&&(r.date||'').startsWith(month)).reduce((a,r)=>a+Number(r.value||0),0),expenses:expenses.reduce((a,r)=>a+Number(r.value||0),0),expenseCount:expenses.length,spent,profit:received-spent};}
