import {documentSections,budgetTotal} from './document-content';
import {formatMoney,formatDay} from './studio-types';
export function proposalSheet(pdf:any,entry:any,rows:any[],settings:any,c:any,logo:any,addImage:any){const {ink,accent,background,support,text}=c,layout=entry.pdfLayout||settings.documentDefaults?.layout||'column',client=rows.find(r=>r.id===entry.client),left=layout==='column'?65:20,width=190-left;let page=0,y=0;
 const write=(body:any,x:number,top:number,w:number,size=8,font='Poppins',color=text)=>{pdf.setTextColor(color);pdf.setFont(font);pdf.setFontSize(size);const lines=pdf.splitTextToSize(String(body||''),w);pdf.text(lines,x,top);return top+lines.length*size*.44};
 const header=()=>{if(page++)pdf.addPage();pdf.setFillColor(layout==='editorial'?background:'#FFFFFF');pdf.rect(0,0,210,297,'F');if(layout==='column'){pdf.setFillColor(ink);pdf.rect(0,0,52,297,'F');if(logo)addImage(logo,8,10,12,12);write(settings.title||'NUNES INTERIORES',8,36,36,12,'PoppinsBold','#FFFFFF');write(entry.proposalHeading||'proposta de',8,59,36,7,'Poppins','#FFFFFF');write(entry.proposalTitle||'orçamento',8,72,36,18,'PlayfairItalic','#FFFFFF');write([client?.title,settings.name,settings.email,settings.phone].filter(Boolean).join('\n\n'),8,95,36,7,'Poppins','#FFFFFF');y=24;}else if(layout==='band'){pdf.setFillColor(ink);pdf.rect(0,0,210,58,'F');if(logo)addImage(logo,20,8,10,10);write(entry.proposalHeading||'proposta de',20,26,170,7,'Poppins','#FFFFFF');write(entry.proposalTitle||'orçamento',20,39,170,24,'Playfair','#FFFFFF');write([client?.title,formatDay(entry.date),'#'+String(entry.number||1).padStart(3,'0')].filter(Boolean).join('    ·    '),20,51,170,7,'Poppins','#FFFFFF');y=72;}else if(layout==='editorial'){if(logo)addImage(logo,20,10,10,10);write(entry.proposalHeading||'proposta de',20,30,170,7,'Poppins',accent);write(entry.proposalTitle||'orçamento',20,47,170,30,'PlayfairItalic',ink);write('#'+String(entry.number||1).padStart(3,'0'),20,62,170,22,'PlayfairItalic',accent);y=78;}else{if(logo)addImage(logo,20,10,10,10);write(settings.title||'NUNES INTERIORES',36,18,110,9,'PoppinsBold');write('ORÇAMENTO',20,37,135,18,'PoppinsBold');write('#'+String(entry.number||1).padStart(3,'0'),155,37,35,14,'Poppins',accent);y=50;}if(layout!=='band'){write([client?.title,formatDay(entry.date)].filter(Boolean).join(' · '),left,y,width,7);y+=10;}pdf.setDrawColor(support);pdf.line(left,y,190,y);y+=9;};header();
 const ensure=(space:number)=>{if(y+space>270)header()};
 write(entry.title,left,y,width,10,'PoppinsBold');y+=12;
 const items=entry.items?.length?entry.items:[{title:entry.serviceType||entry.title,quantity:1,unitValue:entry.value||0,description:entry.scope}];
 items.forEach((item:any,i:number)=>{const lines=pdf.splitTextToSize([item.description,item.deliverables,item.term].filter(Boolean).join('\n'),width-36);ensure(15);write(String(i+1).padStart(2,'0'),left,y,8,7,'Poppins',accent);const titles=pdf.splitTextToSize(item.title,width-40);write(titles.join('\n'),left+10,y,width-40,9,'PoppinsBold');write(formatMoney(Number(item.quantity)*Number(item.unitValue)),155,y,35,8,'PoppinsBold');y+=Math.max(9,titles.length*4.5);write(item.quantity+' × '+formatMoney(item.unitValue),left+10,y,width-15,7,'Poppins',accent);y+=7;for(const line of lines){ensure(5);write(line,left+10,y,width-15,7);y+=4;}y+=6;pdf.setDrawColor(support);pdf.line(left,y,190,y);y+=9;});
 ensure(22);pdf.setFillColor(support);pdf.rect(left,y-3,width,14,'F');write('INVESTIMENTO TOTAL',left+3,y+5,width-40,7,'PoppinsBold');write(formatMoney(budgetTotal(entry)),151,y+5,36,10,'PoppinsBold');y+=24;
 const sections=documentSections(entry,rows,settings).filter((s:any)=>!['Proposta para','Investimento e pagamento'].includes(s.title)&&!/^\d+\. /.test(s.title));sections.push({title:'Pagamento',body:[entry.installments?'Pagamento em '+entry.installments+' parcela(s).':'',entry.payment,Number(entry.discount)>0?'Desconto: '+formatMoney(entry.discount):''].filter(Boolean).join('\n')});
 for(const section of sections){const lines=pdf.splitTextToSize(section.body,width);ensure(13);write(section.title.toUpperCase(),left,y,width,7,'PoppinsBold',accent);y+=7;for(const line of lines){ensure(5);write(line,left,y,width,7);y+=4;}y+=8;}
 for(let i=1;i<=pdf.getNumberOfPages();i++){pdf.setPage(i);write([settings.phone,settings.email].filter(Boolean).join(' · '),left,284,width-15,6,'Poppins',accent);write(i+' / '+pdf.getNumberOfPages(),179,284,12,6,'Poppins',accent)}return pdf;}
