import {budgetTotal} from './document-content';
import {formatMoney,formatDay} from './studio-types';
// The proposal uses the budget snapshot, never today's editable service rates.
export function proposalSlides(pdf:any,entry:any,client:any,settings:any,colors:any,logo:any,photos:any[],addImage:any){
 const {ink,accent,background,support,text}=colors,W=297,H=167.0625;let page=0;const steps=entry.processSnapshot?.steps||[],total=budgetTotal(entry),days=steps.reduce((a:number,s:any)=>a+Number(s.days||0),0);
 const write=(body:any,x:number,y:number,width:number,size=10,font='Poppins',color=text)=>{pdf.setFont(font);pdf.setFontSize(size);pdf.setTextColor(color);const lines=pdf.splitTextToSize(String(body||''),width);pdf.text(lines,x,y);return y+lines.length*size*.43};
 const base=()=>{if(page++)pdf.addPage([W,H],'landscape');pdf.setFillColor(background);pdf.rect(0,0,W,H,'F');pdf.setTextColor(support);pdf.setFont('Playfair');pdf.setFontSize(110);pdf.text(String(page).padStart(2,'0'),286,51,{align:'right'});pdf.setDrawColor(accent);pdf.setLineWidth(.5);pdf.line(20,14,34,14);if(logo)addImage(logo,279,6,10,10);pdf.setDrawColor(support);pdf.setLineWidth(.15);pdf.line(20,155,277,155);write([settings.phone,settings.email].filter(Boolean).join(' · '),20,160,220,6,'Poppins',accent);};
 const heading=(label:string,title:string)=>{base();write(label.toUpperCase(),20,27,220,7,'PoppinsBold',accent);write(title,20,43,250,25,'PlayfairItalic',ink)};
 const panel=(x:number,y:number,w:number,h:number,color=support)=>{pdf.setFillColor(color);pdf.roundedRect(x,y,w,h,5,5,'F')};
 const content=(title:string,body:string)=>{const lines=pdf.splitTextToSize(body,245);for(let i=0;i<lines.length;i+=18){heading(i?title+' · continuação':title,title);write(lines.slice(i,i+18).join('\n'),20,62,245,11);}};
 base();write('PROPOSTA #'+String(entry.number||1).padStart(3,'0'),20,54,130,7,'PoppinsBold',accent);write(entry.title||'Projeto de interiores',20,76,132,34,'PlayfairItalic',ink);write('Preparada para '+(client?.title||'Cliente a definir'),20,116,130,11);write(formatDay(entry.date),20,125,130,8,'Poppins',accent);panel(166,19,111,130,support);if(photos[0])addImage(photos[0],166,19,111,130);else{pdf.setDrawColor(accent);pdf.setLineWidth(.25);pdf.roundedRect(182,57,80,92,40,40,'S');pdf.roundedRect(197,85,50,64,25,25,'S');pdf.setFillColor(accent);pdf.roundedRect(208,108,28,41,14,14,'F');}
 heading('A proposta','O seu projeto');write(entry.description||'Esta proposta reúne o escopo, as etapas, os prazos e o investimento do seu projeto. Cada entrega será alinhada com você ao longo do trabalho.',20,71,135,12);panel(168,64,108,25);write('CLIENTE',173,72,98,7,'PoppinsBold',accent);write(client?.title||'Cliente a definir',173,81,98,11);panel(168,95,51,25);write('PRAZO ESTIMADO',173,103,43,6,'PoppinsBold',accent);write(days?days+' dias':'A combinar',173,113,43,10);panel(225,95,51,25);write('ETAPAS',230,103,40,6,'PoppinsBold',accent);write(steps.length||'A combinar',230,113,40,10);
 if(steps.length){
 // Split long descriptions into continuation cards so all scope remains in the PDF.
 const cards:any[]=[];steps.forEach((s:any,i:number)=>{const body=[s.description,s.includes].filter(Boolean).join('\n'),lines=pdf.splitTextToSize(body,43);for(let j=0;j<Math.max(1,lines.length);j+=16)cards.push({...s,index:i,body:lines.slice(j,j+16).join('\n'),continuation:j>0});});
 for(let start=0;start<cards.length;start+=5){heading('Como vamos trabalhar','Etapas do projeto');cards.slice(start,start+5).forEach((s:any,i:number)=>{const x=20+i*52;panel(x,54,49,96);write(String(s.index+1).padStart(2,'0')+(s.continuation?' +':''),x+3,64,43,20,'Playfair',accent);write(s.title,x+3,75,43,9,'PoppinsBold');write(s.body,x+3,90,43,7);write(s.days+' dias '+s.dayType,x+3,141,43,6);write(s.payment+'%',x+34,146,12,7,'PoppinsBold',accent);});}
 for(let start=0;start<steps.length;start+=6){heading('Quanto tempo leva','Prazos e etapas');const chunk=steps.slice(start,start+6),duration=Math.max(1,days);let passed=steps.slice(0,start).reduce((a:number,s:any)=>a+Number(s.days||0),0);chunk.forEach((s:any,i:number)=>{const y=60+i*13;write(s.title,20,y+6,70,9);panel(94,y,183,10,support);const w=Math.max(6,183*Number(s.days||0)/duration),x=94+183*passed/duration;panel(x,y,Math.min(w,277-x),10,accent);write(s.days+' dias '+s.dayType,97,y+6,177,7,'Poppins',ink);passed+=Number(s.days||0);});write('Prazos contados após as informações e aprovações necessárias. '+(entry.term||''),20,145,250,7);}
 }
 heading('Investimento','O que está incluído');panel(20,55,110,92,accent);write('INVESTIMENTO TOTAL',28,91,94,8,'PoppinsBold','#FFFFFF');write(formatMoney(total),28,113,94,27,'Playfair','#FFFFFF');const summary=[entry.scope,...(entry.items||[]).map((i:any)=>[i.title,i.description,i.deliverables,formatMoney(i.quantity*i.unitValue)].filter(Boolean).join(' · '))].filter(Boolean).join('\n\n')||entry.serviceType||entry.title;const summaryLines=pdf.splitTextToSize(summary,132);write(summaryLines.slice(0,20).join('\n'),142,65,132,9);if(summaryLines.length>20)content('Escopo completo',summaryLines.slice(20).join('\n'));
 const payments=steps.filter((s:any)=>Number(s.payment)>0);if(payments.length&&entry.paymentScheduleMode!=='Parcelas mensais'){for(let start=0;start<payments.length;start+=4){heading('Investimento em partes','Forma de pagamento');payments.slice(start,start+4).forEach((s:any,i:number)=>{const x=20+i*65;panel(x,63,61,14,accent);write(s.payment+'%',x+4,72,53,11,'PoppinsBold','#FFFFFF');write(s.title,x,90,60,10);write(formatMoney(total*Number(s.payment)/100),x,113,60,17,'Playfair');});write(entry.payment||'Conforme as condições acordadas na proposta.',20,138,250,9)}}else content('Forma de pagamento',[entry.installments?'Pagamento em '+entry.installments+' parcela(s).':'',entry.payment,entry.firstDue?'Primeiro vencimento: '+formatDay(entry.firstDue):''].filter(Boolean).join('\n\n'));
 content('Observações',[`Inclui ${entry.adjustments??2} rodada(s) de ajustes. Alterações de escopo serão combinadas à parte.`,entry.deliveryFormats?'Entrega: '+entry.deliveryFormats:'',entry.validity?'Proposta válida até '+formatDay(entry.validity):'',entry.notes].filter(Boolean).join('\n\n'));
 heading('Próximos passos','Vamos começar?');write('01  Aprovação da proposta\n\n02  Contrato e pagamento acordado\n\n03  Briefing e início do trabalho',20,72,130,12);panel(164,55,113,92,accent);write([settings.name||'NUNES INTERIORES',settings.phone,settings.email,settings.instagram].filter(Boolean).join('\n\n'),174,79,93,11,'Poppins','#FFFFFF');
 if(entry.studioAbout)content('Sobre o estúdio',entry.studioAbout);photos.slice(1).filter(Boolean).forEach((photo:any)=>{heading('Nunes Interiores','Projetos do estúdio');addImage(photo,20,54,257,96)});
 for(let i=1;i<=pdf.getNumberOfPages();i++){pdf.setPage(i);write(`${i} / ${pdf.getNumberOfPages()}`,260,160,17,6,'Poppins',accent)}
 return pdf;
}
