import {Entry,formatDay,formatMoney} from './studio-types';
import {budgetTotal} from './document-content';

export const referenceModels=[{id:'contract-final',title:'Contrato · cliente final',kind:'contracts',audience:'Cliente final',description:'Modelo de projeto de interiores, com a disposição e as cláusulas do contrato enviado.'},{id:'contract-freelancer',title:'Contrato · freelancer',kind:'contracts',audience:'Freelancer',description:'Modelo de prestação de serviços freelancer, com etapas, ajustes e entregas.'},{id:'proposal-nunes',title:'Proposta · apresentação Nunes',kind:'budgets',audience:'Cliente final',description:'Seis páginas com a capa e as imagens originais. Edite entregas, valores, pagamento e prazos.'}];
const cache=new Map<string,Promise<any>>();
export function referenceAsset(name:string):Promise<any>{if(!cache.has(name))cache.set(name,fetch('/reference-templates/'+name+'.json').then(async r=>{if(!r.ok)throw Error('Não foi possível carregar o modelo. Atualize a página e tente novamente.');return r.json();}).catch(e=>{cache.delete(name);throw e}));return cache.get(name)!;}
export function referenceVariables(entry:Entry,rows:Entry[],settings:any){const c=rows.find(r=>r.id===entry.client),p=rows.find(r=>r.id===entry.project);return {cliente:c?.title||entry.clientName||'[Nome do cliente]',cpf:c?.tax||'[CPF/CNPJ]',endereco:c?.address||'[Endereço do cliente]',email:c?.email||'[E-mail do cliente]',telefone:c?.phone||'[Telefone do cliente]',responsavel:settings.name||'[Nome da responsável]',cpf_estudio:settings.tax||'[CPF/CNPJ da responsável]',endereco_estudio:settings.address||'[Endereço do estúdio]',email_estudio:settings.email||'[E-mail do estúdio]',telefone_estudio:settings.phone||'[Telefone do estúdio]',estudio:String(settings.title||'Nunes Interiores').toUpperCase(),projeto:entry.projectName||p?.title||entry.title||'[Projeto]',endereco_projeto:entry.projectAddress||p?.address||'[Endereço do imóvel]',ambientes:entry.rooms||p?.rooms||'[Ambientes contratados]',valor:formatMoney(budgetTotal(entry)),pagamento:entry.payment||'[Condições de pagamento]',dados_bancarios:entry.bankDetails||settings.bankDetails||'[Dados para pagamento]',prazo_final:formatDay(entry.deadline),data:formatDay(entry.date),escopo:entry.scope||'[Escopo contratado]',prazos:entry.term||'[Etapas e prazos]',ajustes:String(entry.adjustments??2)};}
export function resolveTemplateText(text:string,entry:Entry,rows:Entry[],settings:any){const vars:any=referenceVariables(entry,rows,settings);return String(text||'').replace(/\{\{([a-z_]+)\}\}/g,(token,key)=>vars[key]??token);}
export async function applyReferenceModel(id:string,update:(key:string,value:any)=>void,draft?:Entry){const model=referenceModels.find(m=>m.id===id);if(!model)return;update('referenceTemplate',id);if(id.startsWith('contract-')){const data=await referenceAsset(id);const paragraphs:any=Object.fromEntries(data.paragraphs.map((p:any)=>[p.index,p.text]));const sourceFirst=data.paragraphs.findIndex((p:any)=>p.text==='A PRESTADORA realizará:'||p.text==='Estão incluídos no serviço:');if(draft?.scope&&sourceFirst>=0){paragraphs[data.paragraphs[sourceFirst].index]='{{escopo}}';for(let i=sourceFirst+1;i<data.paragraphs.length&&data.paragraphs[i].text.startsWith('•');i++)paragraphs[data.paragraphs[i].index]='';}update('referenceParagraphs',paragraphs);update('audience',model.audience);}else{update('presentation','slides');update('allowPDF',true);if(!draft?.scope&&!draft?.items?.length)update('scope','Planta de layout completa com cotas\nPlanta de gesso e iluminação\nIndicações de pontos elétricos e hidráulicos\nMaquete eletrônica e arquivo finalizado\nDetalhamentos gerais de marcenaria, marmoraria e moodboard com cores\nImagens renderizadas');if(!draft?.term)update('term','1ª etapa — estudo do espaço, modelagem e renders: 20 dias úteis.\n2ª etapa — após aprovação: 20 dias úteis para montagem do caderno e entrega final.');}}
const xmlEscape=(text:string)=>text.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
/** Reuse the original OOXML package, including styles, tables, margins, headers and footers. */
export async function referenceWordBytes(entry:Entry,rows:Entry[],settings:any){const {unzipSync,zipSync,strToU8,strFromU8}=await import('fflate'),data=await referenceAsset(entry.referenceTemplate),files=unzipSync(Uint8Array.from(atob(data.docx),(c:string)=>c.charCodeAt(0)));let index=0;files['word/document.xml']=strToU8(strFromU8(files['word/document.xml']).replace(/<w:p(?:\s[^>]*?)?(?:\/>|>[\s\S]*?<\/w:p>)/g,(paragraph)=>{const p=data.paragraphs[index++];if(!p)return paragraph;const source=entry.referenceParagraphs?.[p.index]??p.text,text=resolveTemplateText(source,entry,rows,settings);if(!p.text&&!text)return paragraph;const props=paragraph.match(/<w:pPr(?:\s[^>]*)?>[\s\S]*?<\/w:pPr>/)?.[0]||'',runProps=paragraph.match(/<w:rPr(?:\s[^>]*)?>[\s\S]*?<\/w:rPr>/)?.[0]||'';if(source===p.text){return paragraph.replace(/\{\{[a-z_]+\}\}/g,t=>xmlEscape(resolveTemplateText(t,entry,rows,settings))); }return paragraph.slice(0,paragraph.indexOf('>')+1)+props+'<w:r>'+runProps+text.split('\n').map((line:string,i:number)=>(i?'<w:br/>':'')+'<w:t xml:space="preserve">'+xmlEscape(line)+'</w:t>').join('')+'</w:r></w:p>';}));for(const name of Object.keys(files))if(name.endsWith('.xml')&&name!=='word/document.xml')files[name]=strToU8(strFromU8(files[name]).replace(/\{\{[a-z_]+\}\}/g,t=>xmlEscape(resolveTemplateText(t,entry,rows,settings))));return zipSync(files);}
export async function downloadReferenceWord(entry:Entry,rows:Entry[],settings:any){const bytes=await referenceWordBytes(entry,rows,settings);const url=URL.createObjectURL(new Blob([bytes as BlobPart],{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}));const a=document.createElement('a');a.href=url;a.download=(entry.title||'Contrato')+'.docx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
