import {Entry,formatMoney} from './studio-types';
import {budgetTotal} from './document-content';
import {referenceAsset,resolveTemplateText,contractParagraphText} from './reference-templates';
export const defaultProposalDeliveries='Planta de layout completa com cotas\nPlanta de gesso e iluminação\nIndicações de pontos elétricos e hidráulicos\nMaquete eletrônica e arquivo finalizado\nDetalhamentos gerais de marcenaria, marmoraria e moodboard com cores\nImagens renderizadas';
export const defaultProposalTerms='1ª etapa — estudo do espaço, modelagem e renders: 20 dias úteis.\n2ª etapa — após aprovação: 20 dias úteis para montagem do caderno e entrega final.';
export const defaultProposalConditions='O prazo será contabilizado a partir do recebimento de todas as informações, medidas, referências e definições necessárias para o desenvolvimento do projeto. O andamento da etapa seguinte fica condicionado à aprovação da etapa anterior.';
async function font(pdf:any,name:string,file:string){const r=await fetch('/fonts/'+file+'.ttf');if(!r.ok)throw Error('Não foi possível carregar a fonte do modelo.');const bytes=new Uint8Array(await r.arrayBuffer());let raw='';for(const b of bytes)raw+=String.fromCharCode(b);pdf.addFileToVFS(name+'.ttf',btoa(raw));pdf.addFont(name+'.ttf',name,'normal');}
export async function makeReferencePDF(entry:Entry,rows:Entry[],settings:any){const {jsPDF}=await import('jspdf');if(entry.referenceTemplate==='proposal-nunes'){
 const pdf=new jsPDF({unit:'pt',format:[960,540],orientation:'landscape'}),assets=await Promise.all([1,2,3,4,5,6].map(n=>referenceAsset('proposal-page-'+n))),embedded=await referenceAsset('proposal-fonts');await font(pdf,'Poppins','poppins-normal-400');await font(pdf,'PoppinsBold','poppins-normal-600');for(const [name,f] of Object.entries(embedded) as any){pdf.addFileToVFS(name+'.ttf',f.data);pdf.addFont(name+'.ttf',name,'normal');}
 const select=(text:string,name:string)=>{const f=embedded[name];pdf.setFont(f&&[...text].every(c=>c==='\n'||f.characters.includes(c))?name:name.endsWith('Bold')?'PoppinsBold':name.endsWith('Italic')?'PoppinsItalic':'Poppins');};
 const background=(n:number,add=true)=>{if(add)pdf.addPage([960,540],'landscape');pdf.addImage(assets[n-1].image,'JPEG',0,0,960,540);};
 const text=(body:string,x:number,y:number,width:number,size=14,fontName='CenturyGothic',color='#000000',spacing=1.2)=>{select(body,fontName);pdf.setFontSize(size);pdf.setTextColor(color);const lines=pdf.splitTextToSize(body,width);pdf.text(lines,x,y,{lineHeightFactor:spacing});return y+lines.length*size*spacing;};
 const flow=(body:string,x:number,y:number,width:number,size:number,bg:number,fontName='CenturyGothic',limit=490)=>{for(const paragraph of body.split('\n')){select(paragraph,fontName);pdf.setFontSize(size);const lines=pdf.splitTextToSize(paragraph,width);for(const line of lines){if(y>limit){background(bg);y=130;}text(line,x,y,width,size,fontName);y+=size*1.2;}y+=size*.4;}return y;};
 background(1,false);background(2);const about=entry.referenceAbout||'Sou designer de interiores e acredito que cada ambiente deve unir beleza, funcionalidade e personalidade.\n\nDesenvolvo projetos residenciais e comerciais pensados para atender às necessidades e ao estilo de cada cliente e profissional, transformando espaços em ambientes que fazem sentido para quem os vive.';pdf.setFont('Poppins');pdf.setFontSize(14.04);let aboutY=133.4;for(const line of pdf.splitTextToSize(about,410)){if(aboutY>315){background(2);aboutY=133.4;}text(line,472.54,aboutY,410,14.04,'Poppins');aboutY+=25.2;}text('Será um prazer fazer parte do seu projeto.',472.54,335,410,14.04,'PoppinsBold');pdf.setFont('PoppinsItalic');pdf.setFontSize(14.04);pdf.text('Com carinho,',880,410,{align:'right'});pdf.setFont('PoppinsBold');pdf.text(settings.name||'Lara Nunes',880,460,{align:'right'});pdf.setFont('PoppinsItalic');pdf.text(settings.title||'Nunes Interiores',880,485,{align:'right'});
 background(3);pdf.setFont('Poppins');pdf.setFontSize(18);pdf.setTextColor('#4E3D31');pdf.text((entry.referenceServiceTitle||entry.serviceType||'PROJETO DE INTERIORES').toUpperCase(),860,204.5,{align:'right',maxWidth:400});text(entry.referenceService||'Desenvolvimento completo de projetos de interiores residenciais e comerciais, contemplando briefing, levantamento e estudo das necessidades, definição de layout, materiais e acabamentos, modelagem 3D, imagens renderizadas e detalhamentos técnicos necessários para a execução.',485.81,237.5,375,14.04,'Poppins','#808080',1.8);
 background(4);const client=rows.find(c=>c.id===entry.client),name=client?.title||entry.clientName||'[Nome do cliente]';pdf.setFont('Poppins');let nameSize=27.96;pdf.setFontSize(nameSize);while(pdf.getTextWidth(name)>420&&nameSize>20){nameSize-=1;pdf.setFontSize(nameSize);}const nameLines=pdf.splitTextToSize(name,420);pdf.setTextColor('#AF7D1C');pdf.text(nameLines,810,74,{align:'right'});const subtitleY=74+nameLines.length*nameSize*1.2;pdf.setFontSize(15.96);pdf.setTextColor('#000000');pdf.text(entry.referenceSubtitle||[entry.audience||'Cliente final',entry.projectName||entry.serviceType||'Projeto de interiores'].join(' – '),810,Math.max(97,subtitleY),{align:'right',maxWidth:420});let y=Math.max(145,subtitleY+40);const delivery=entry.scope||(entry.items||[]).map((i:any)=>[i.title,i.deliverables||i.description].filter(Boolean).join(' — ')).join('\n')||defaultProposalDeliveries;for(const item of delivery.split('\n').filter(Boolean)){select(item,'CenturyGothic');pdf.setFontSize(18);const lines=pdf.splitTextToSize(item.replace(/^[•\-]\s*/,''),410);if(y+lines.length*21>490){background(4);y=145;}pdf.setDrawColor('#000000');pdf.rect(460,y-11,10,10);y=flow(item.replace(/^[•\-]\s*/,''),482,y,410,18,4);y+=3;}if(entry.rooms)flow('Ambientes: '+entry.rooms,482,y+16,410,18,4);
 background(5);let pos=text(entry.referenceServiceTitle||entry.serviceType||'Projeto de interiores completo',439.25,170,464,14.04);pos+=13;pos=text('Investimento total: '+formatMoney(budgetTotal(entry)),439.25,pos,464,14.04,'PoppinsBold');if(entry.cashValue!==''&&entry.cashValue!==undefined&&entry.cashValue!==null)pos=text('Pagamento à vista via PIX: '+formatMoney(entry.cashValue),439.25,pos,464,14.04,'PoppinsBold');pos+=3;pos=text('FORMA DE PAGAMENTO:',439.25,pos,464,14.04,'CenturyGothic-Bold');pos+=1;pos=flow(entry.payment||(entry.installments>1?`Pagamento em ${entry.installments} parcelas.`:'50% na contratação e 50% na entrega final.'),439.25,pos,464,14.04,5);pos+=10;pos=text('Prazos:',439.25,pos,464,14.04,'CenturyGothic-Bold');pos+=1;pos=flow(entry.term||defaultProposalTerms,439.25,pos,464,14.04,5);flow(entry.referenceConditions||defaultProposalConditions,439.25,pos+10,464,14.04,5,'CenturyGothic-Italic');background(6);return pdf;
 }
 const model=await referenceAsset(entry.referenceTemplate),page=model.page,pdf=new jsPDF({unit:'mm',format:[page.width,page.height]}),scale=25.4/72,width=page.width-page.left-page.right;let y=page.top+23;const final=entry.referenceTemplate==='contract-final';
 const header=()=>{pdf.setTextColor('#70513E');pdf.setFont(final?'times':'helvetica','bold');pdf.setFontSize(9);pdf.text(String(settings.title||'NUNES INTERIORES').toUpperCase(),page.width-page.right,12,{align:'right'});pdf.setDrawColor('#BBBBBB');pdf.setLineWidth(.15);pdf.line(page.left,page.top+10,page.width-page.right,page.top+10);};header();const next=()=>{pdf.addPage([page.width,page.height]);header();y=page.top+23;};
 for(const p of model.paragraphs){if(p.role==='brand')continue;const source=contractParagraphText(model,p,entry),body=resolveTemplateText(source,entry,rows,settings);if(p.pageBreak&&y>page.top+25)next();if(!body.trim())continue;const run=p.runs.find((r:any)=>r.text)||{},title=body==='contrato',heading=p.style.toLowerCase().startsWith('heading')||/^\d+\. [A-ZÁÉÍÓÚÇ ]+$/.test(body),size=title?26:run.size||9,face=title||run.font==='Georgia'?'times':final?'times':'helvetica',style=title||run.italic?'italic':heading||p.runs.filter((r:any)=>r.text.trim()).every((r:any)=>r.bold)?'bold':'normal';y+=(p.before||0)*scale+(title?7:0);pdf.setFont(face,style);pdf.setFontSize(size);pdf.setTextColor(heading||body==='DOCUMENTO'?'#70513E':run.color||'#373737');const lines=pdf.splitTextToSize(body,width),lineHeight=size*scale*1.35;if((title||heading)&&y+(lines.length+2)*lineHeight>page.height-page.bottom-10)next();for(const line of lines){if(y+lineHeight>page.height-page.bottom-10)next();pdf.setFont(face,style);pdf.setFontSize(size);pdf.text(line,page.left,y);y+=lineHeight;}y+=(p.after||4)*scale+(title?6:0);
 }
 for(let i=1;i<=pdf.getNumberOfPages();i++){pdf.setPage(i);pdf.setFont('helvetica','normal');pdf.setFontSize(7);pdf.setTextColor('#777777');pdf.text(`${i} / ${pdf.getNumberOfPages()}`,page.width-page.right,page.height-8,{align:'right'});pdf.text((settings.title||'NUNES INTERIORES')+' · CONTRATO DE PRESTAÇÃO DE SERVIÇOS',page.left,page.height-8);}return pdf;
}
