import {Entry,formatMoney,formatDay} from './studio-types';
import {budgetTotal} from './document-content';
export const messageDefaults:Record<string,string>={
 contact:'Olá, {cliente}! Aqui é {meu_nome}, da {estudio}. Obrigada pelo contato.\n\nMe conte sobre o projeto: o que você precisa, a metragem ou quantidade e o prazo desejado. Com essas informações, preparo o orçamento.',
 proposal:'Olá, {cliente}! Segue a proposta {proposta} para {projeto}, no valor de {valor}. Ela apresenta o escopo, as entregas, os prazos e as condições de pagamento. Estou à disposição para esclarecer suas dúvidas.',
 followup:'Olá, {cliente}! Tudo bem? Você conseguiu analisar a proposta {proposta} para {projeto}? Se precisar esclarecer algum ponto ou ajustar o escopo, podemos conversar.',
 approved:'Olá, {cliente}! Obrigada pela aprovação de {projeto}. Para reservar o início do trabalho, seguiremos com o contrato e o pagamento da entrada conforme a proposta. Pix: {pix}. Após a confirmação, alinharemos o briefing.',
 briefing:'Olá, {cliente}! Para iniciar {projeto}, preciso do briefing, das medidas e dos arquivos de referência combinados. O prazo previsto é {prazo} e começa conforme as condições da proposta.',
 payment:'Olá, {cliente}! Lembrete da parcela {parcela} de {projeto}, no valor de {valor_parcela}, com vencimento em {vencimento}. Pix: {pix}. Se já realizou o pagamento, por favor envie o comprovante.',
 delivery:'Olá, {cliente}! A entrega de {projeto} está pronta. Arquivos: {arquivos}. Confira o material e reúna suas observações para a rodada de ajustes prevista na proposta.'
};
export const messageLabels:Record<string,string>={contact:'Primeiro contato',proposal:'Envio do orçamento',followup:'Retorno do orçamento',approved:'Orçamento aprovado · pedir entrada',briefing:'Solicitação de briefing',payment:'Lembrete de pagamento',delivery:'Entrega do projeto'};
export const messageVariables=['cliente','projeto','valor','proposta','parcela','valor_parcela','vencimento','prazo','arquivos','pix','meu_nome','estudio','site','instagram'];
export function renderMessage(template:string,record:Entry,rows:Entry[],settings:any){const client=record.kind==='clients'?record:rows.find(r=>r.id===record.client),project=rows.find(r=>r.id===record.project),budget=record.kind==='budgets'?record:rows.find(r=>r.kind==='budgets'&&(r.id===record.budget||r.client===client?.id&&r.project===project?.id)),vars:any={cliente:client?.title,projeto:project?.title||budget?.title||record.title,valor:formatMoney(budgetTotal(budget||record)),proposta:budget?.number?'#'+String(budget.number).padStart(3,'0'):budget?.title,parcela:record.installmentNumber||record.parcel,valor_parcela:record.kind==='finance'?formatMoney(record.value):undefined,vencimento:record.kind==='finance'?formatDay(record.date):undefined,prazo:record.term||budget?.term,arquivos:record.deliveryFormats||budget?.deliveryFormats,pix:settings.pix,meu_nome:settings.name,estudio:settings.title,site:settings.site,instagram:settings.instagram};return template.replace(/\{\{?(\w+)\}\}?/g,(whole,key)=>vars[key]!==undefined&&vars[key]!==''?String(vars[key]):whole)}
