import {Entry} from './studio-types';
export const appearanceDefaults={font:'Poppins',displayFont:'Playfair Display',color:'#2F2F2F',supportColor:'#CDB89C',italicColor:'#9B8264',backgroundColor:'#F6F2EC',cardColor:'#FFFFFF',textColor:'#2A2A2A',cornerRadius:18,appearanceVersion:2};
export const pricingDefaults={urgency:30,extraFloor:50,editableFile:30,studentDiscount:40,simple:1,medium:1.3,high:1.6};
export const documentDefaults={presentation:'slides',layout:'column',heading:'proposta de',title:'orçamento',term:'O prazo começa após a aprovação e o recebimento das informações necessárias.',deliveryFormats:'PDF e arquivos previstos no escopo.',payment:'Pix ou transferência — 50% na aprovação + 50% na entrega.',adjustments:2,numberStart:1,paymentMethods:['Pix','Transferência','Cartão de crédito','Boleto','Dinheiro'],cardFee:0,usePDF:true,useContracts:true,useInstagram:false,about:'',photos:[]};
export type StudioService={id:string;title:string;category:string;unit:string;value:number;fixed:number;minimum:number;packageQuantity:number;packageValue:number;audience:string;extraFloor:boolean;description:string};
export function defaultServices():StudioService[]{return [['hour','hora de trabalho','Avulsos','hora'],['render','imagem 3D (render)','3D e visualização','imagem'],['model','modelagem 3D','3D e visualização','m²'],['plan','planta humanizada','3D e visualização','planta'],['interiors','projeto de interiores','Projetos e desenho técnico','m²'],['technical','desenho técnico / executivo','Projetos e desenho técnico','m²'],['board','prancha de apresentação','Apresentação','prancha'],['slides','apresentação em slides','Apresentação','slide'],['diagram','diagramas','Apresentação','diagrama'],['layout','diagramação','Apresentação','prancha'],['custom','serviço personalizado','Seus serviços','unidade']].map(([id,title,category,unit])=>({id,title,category,unit,value:0,fixed:0,minimum:0,packageQuantity:0,packageValue:0,audience:'Os dois',extraFloor:false,description:''}));}
export function studioSettings(stored:any,defaults:any){return {...defaults,...stored,...(stored?.appearanceVersion===2?{}:appearanceDefaults),services:stored?.services||defaultServices(),pricingRules:{...pricingDefaults,...stored?.pricingRules},documentDefaults:{...documentDefaults,...stored?.documentDefaults},workAudience:stored?.workAudience||'Os dois',messages:stored?.messages||{},goals:stored?.goals||{monthly:0,annual:0}};}
export function serviceEstimate(service:StudioService,quantity:number,rules:any,options:any={}){const q=Math.max(0,Number(quantity)||0),r={...pricingDefaults,...rules};let base=q*Number(service.value||0)+Number(service.fixed||0);if(service.packageQuantity>0&&service.packageValue>0&&q>=service.packageQuantity)base=Math.floor(q/service.packageQuantity)*service.packageValue+(q%service.packageQuantity)*service.value+service.fixed;if(service.unit==='m²')base*=Number(r[options.complexity||'simple'])||1;base=Math.max(base,Number(service.minimum)||0);if(service.extraFloor)base*=1+Math.max(0,(Number(options.floors)||1)-1)*Number(r.extraFloor)/100;if(options.urgent)base*=1+Number(r.urgency)/100;if(options.editable)base*=1+Number(r.editableFile)/100;if(options.audience==='Estudante')base*=Math.max(0,1-Number(r.studentDiscount)/100);return Math.round(base*100)/100;}
export function proposalDefaults(settings:any):Partial<Entry>{const d={...documentDefaults,...settings.documentDefaults};return {presentation:d.presentation,pdfLayout:d.layout,proposalHeading:d.heading,proposalTitle:d.title,term:d.term,payment:d.payment,deliveryFormats:d.deliveryFormats,adjustments:d.adjustments,number:Math.max(Number(d.numberStart)||1,1),studioAbout:d.about,studioPhotos:d.photos,allowPDF:d.usePDF,createContract:d.useContracts};}
