import {paymentPlanError,linkedReceipts} from './payment-plan';
import {Entry,defaultStages} from './studio-types';
import {proposalDefaults,studioSettings} from './studio-settings';
import {budgetTotal,defaultClauses} from './document-content';
import {installmentPlan} from './installments';
import {scheduledSteps,stagePayments,processError,defaultProcesses} from './work-processes';
export const normalizedName=(value:any)=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().replace(/\s+/g,' ').toLowerCase();
export const projectName=(r:Entry)=>r.projectName||r.title.replace(/^(orçamento|proposta|contrato)\s*[·:\-–]\s*/i,'');
export function workKey(value:string){let n=2166136261;for(const c of normalizedName(value))n=Math.imul(n^c.charCodeAt(0),16777619);return (n>>>0).toString(36);}
export function matchingProject(client:string,name:string,rows:Entry[]){return rows.find(r=>r.kind==='projects'&&!r.deleted&&!r.archived&&r.client===client&&normalizedName(projectName(r))===normalizedName(name));}
export function demandCards(rows:Entry[]){const active=rows.filter(r=>!r.deleted&&!r.archived),seen=new Set<string>();return active.filter(r=>r.kind==='projects'||r.kind==='tasks'&&!r.project&&r.category!=='Lembrete').filter(r=>{const key=(r.client||r.id)+'|'+normalizedName(projectName(r));if(seen.has(key))return false;seen.add(key);return true;});}
export function buildBudgetIntegration(budget:Entry,rows:Entry[],date:string){if(!budget.client)throw Error('Vincule um cliente antes de fechar o pedido.');const existing=rows.find(r=>r.id===budget.project&&r.kind==='projects')||matchingProject(budget.client,projectName(budget),rows);if(existing?.deleted)throw Error('Restaure o projeto antes de fechar o pedido.');const snapshot=budget.processSnapshot;if(snapshot){const error=processError(snapshot);if(error)throw Error(error);}const scheduled=snapshot?scheduledSteps(snapshot.steps,budget.startDate||date):[];const value=budgetTotal(budget),prefix='gen-'+budget.id,projectId=existing?.id||prefix+'-project';const stages=existing?.stages?.length?existing.stages:scheduled.length?scheduled:defaultStages();const shared={client:budget.client,project:projectId,budget:budget.id};const generated:Entry[]=[];const client=rows.find(r=>r.id===budget.client&&r.kind==='clients');if(client&&client.initialBudgetId===budget.id&&client.dealStatus!=='Pedido fechado')generated.push({...client,dealStatus:'Pedido fechado'});const scope=[budget.scope,...(budget.items||[]).map((i:any)=>[i.title,i.description,i.deliverables].filter(Boolean).join(' — '))].filter(Boolean).join('\n\n');
if(!existing)generated.push({id:projectId,kind:'projects',title:projectName(budget),...shared,value,audience:budget.audience||'Cliente final',workflowStatus:budget.demandStatus||'Em execução',status:budget.demandStatus==='Entregue'?'Concluído':'Modelagem',startDate:budget.startDate||date,deadline:budget.deadline||scheduled.at(-1)?.deadline||'',stages,processSnapshot:snapshot||null,scope,serviceType:budget.serviceType||snapshot?.name||'Projeto de interiores',payment:budget.payment||'',deliveryFormats:budget.deliveryFormats||'',dealStatus:'Pedido fechado'});else if(!existing.dealStatus)generated.push({...existing,dealStatus:'Pedido fechado',value:existing.value||value,audience:existing.audience||budget.audience||'Cliente final',workflowStatus:existing.workflowStatus||'Em execução'});
const contract=rows.find(r=>r.kind==='contracts'&&r.project===projectId&&!r.deleted);if(!contract&&budget.createContract!==false)generated.push({id:prefix+'-contract',kind:'contracts',title:'Contrato · '+projectName(budget),...shared,status:'Rascunho',date,value,serviceType:budget.serviceType||snapshot?.name||'Projeto de interiores',audience:budget.audience||'Cliente final',scope,term:budget.term||'',payment:budget.payment||'',adjustments:budget.adjustments??2,paymentScheduleMode:budget.paymentScheduleMode||'Por etapas',installments:budget.paymentScheduleMode==='Parcelas mensais'?Number(budget.installments)||1:scheduled.filter(s=>s.payment>0).length||Number(budget.installments)||1,processSnapshot:snapshot||null,deliveryFormats:budget.deliveryFormats||'',clausesList:defaultClauses()});
const receipts=rows.filter(r=>r.kind==='finance'&&r.project===projectId&&r.type==='Receita'&&!r.deleted);const storedPlan=budget.paymentPlan||(client&&(budget.sourceRecord===client.id||client.initialBudgetId===budget.id)?client.paymentPlan:null);const plan=storedPlan&&!paymentPlanError(storedPlan,value)?storedPlan:scheduled.length&&budget.paymentScheduleMode!=='Parcelas mensais'?stagePayments(scheduled,value):installmentPlan(value,Number(budget.installments)||1,budget.firstDue||date);if(!receipts.length)plan.forEach((p:any,i:number)=>generated.push({id:prefix+'-payment-'+i,kind:'finance',...shared,...Object.fromEntries(Object.entries(p).filter(([k])=>!['id','financeId','financeRevision','manualValue'].includes(k))),title:`${projectName(budget)} · ${p.title||'parcela '+(i+1)+'/'+plan.length}`,type:'Receita',status:p.status||'Pendente',paidDate:p.paidDate||'',category:'Projeto',installment:i+1,installments:plan.length,payment:budget.paymentMethod||'A definir',paymentTrigger:p.stage?'Início da etapa':'Data combinada'}));
stages.forEach((s,i)=>{if(!rows.some(r=>r.kind==='tasks'&&r.project===projectId&&r.stage===s.id&&!r.deleted))generated.push({id:prefix+'-task-'+i,kind:'tasks',...shared,title:s.title,stage:s.id,status:'A fazer',priority:'Normal',deadline:s.deadline||budget.deadline||''});});
const dates=scheduled.length?scheduled:budget.deadline?[{id:'delivery',title:'Entrega',deadline:budget.deadline}]:[];dates.forEach((s:any,i:number)=>{if(!rows.some(r=>r.kind==='agenda'&&r.project===projectId&&r.stage===s.id&&!r.deleted))generated.push({id:prefix+(scheduled.length?'-stage-delivery-'+i:'-delivery'),kind:'agenda',...shared,title:s.title+' · '+projectName(budget),date:s.deadline,status:'Agendado',category:'Entrega',stage:s.id});});
return {budget:{...budget,status:'Aprovado',dealStatus:'Pedido fechado',project:projectId,integration:{completed:true,createdAt:new Date().toISOString(),project:projectId,ids:generated.map(r=>r.id)}},generated};}
export function prepareStudioFlow(input:Entry,records:Entry[],date:string){let r={...input};const related:Entry[]=[],rows=[...records],settings=records.find(x=>x.kind==='settings'),processes=settings?.processes||defaultProcesses();const put=(next:Entry)=>{const index=related.findIndex(x=>x.id===next.id);if(index>=0)related[index]=next;else related.push(next);const ri=rows.findIndex(x=>x.id===next.id);if(ri>=0)rows[ri]=next;else rows.push(next);};
if(r.deleted||r.archived)return {record:r,related};
if(r.kind==='clients'&&!r.revision){const same=rows.find(c=>c.kind==='clients'&&!c.deleted&&normalizedName(c.title)===normalizedName(r.title)&&(!r.email||!c.email||normalizedName(r.email)===normalizedName(c.email)));if(same)r={...same,...Object.fromEntries(Object.entries(r).filter(([k,v])=>!['id','revision'].includes(k)&&v!=='')),id:same.id,revision:same.revision};}
if(r.kind==='projects'&&!r.revision&&r.client){const same=matchingProject(r.client,projectName(r),rows);if(same)r={...same};}
if(['budgets','contracts','tasks','agenda','projects'].includes(r.kind)&&!r.client&&r.clientName?.trim()){let client=rows.find(c=>c.kind==='clients'&&!c.deleted&&normalizedName(c.title)===normalizedName(r.clientName));if(!client){client={id:'client-'+r.id,kind:'clients',title:r.clientName.trim(),profession:r.clientProfession||'Cliente particular',clientType:r.audience||'Cliente final',status:'Ativo'};put(client);}r.client=client.id;}
if(r.kind==='tasks'&&r.client&&!r.project&&r.category!=='Lembrete'){const candidates=rows.filter(p=>p.kind==='projects'&&p.client===r.client&&!p.deleted&&!p.archived);let project=r.projectName?matchingProject(r.client,r.projectName,rows):candidates.length===1?candidates[0]:null;if(!r.projectName&&candidates.length>1)throw Error('Escolha o projeto desta tarefa para manter as demandas organizadas.');if(!project){const client=rows.find(c=>c.id===r.client),audience=r.audience||client?.clientType||'Cliente final',snapshot=structuredClone(processes.find((p:any)=>p.audience===audience)||null);project={id:'work-'+r.id,kind:'projects',title:r.projectName||'Projeto de '+(client?.title||'cliente'),client:r.client,status:'Modelagem',workflowStatus:'Em execução',value:r.value||0,audience,processSnapshot:snapshot,stages:snapshot?scheduledSteps(snapshot.steps,date):defaultStages(),deadline:r.deadline||'',startDate:date};put(project);}r.project=project.id;}
if(r.kind==='tasks'&&r.stage&&r.project){const old=records.find(x=>x.id===r.id),project=rows.find(p=>p.id===r.project&&p.kind==='projects');if(old&&old.status!==r.status&&project?.stages?.some(s=>s.id===r.stage)){const finished=['Concluído','Entregue'].includes(r.status),stages=project.stages.map(s=>s.id===r.stage?{...s,status:finished?'Concluída' as const:['A fazer','Em alinhamento'].includes(r.status)?'A iniciar' as const:'Em andamento' as const}:s);const done=stages.every(s=>s.status==='Concluída');put({...project,stages,status:done?'Concluído':project.status==='Concluído'?'Modelagem':project.status,workflowStatus:done?'Entregue':['Em ajustes','Em aprovação','Pendente do cliente / profissional'].includes(r.status)?r.status:project.workflowStatus==='Entregue'?'Em execução':project.workflowStatus||'Em execução'});}}
if(r.kind==='budgets'&&r.client&&!r.project){const same=matchingProject(r.client,projectName(r),rows);if(same)r.project=same.id;}

if((r.kind==='clients'||r.kind==='projects')&&Number(r.value)>0){const name=r.kind==='projects'?projectName(r):r.projectName||projectName(rows.find(b=>b.id===r.initialBudgetId)||{title:'Projeto de '+r.title} as Entry);const client=r.kind==='clients'?r.id:r.client;if(client){const existing=rows.find(b=>b.kind==='budgets'&&!b.deleted&&b.client===client&&((r.kind==='projects'&&b.project===r.id)||normalizedName(projectName(b))===normalizedName(name)));const priorSource=records.find(x=>x.id===r.id),requestedChange=!priorSource||Number(priorSource.value)!==Number(r.value)||priorSource.dealStatus!==r.dealStatus||priorSource.projectName!==r.projectName||priorSource.serviceType!==r.serviceType||priorSource.paymentMethod!==r.paymentMethod||JSON.stringify(priorSource.paymentPlan)!==JSON.stringify(r.paymentPlan);if(r.kind==='clients'&&existing)r.initialBudgetId=existing.id;if(!existing?.integration?.completed&&(!existing||r.kind==='projects'||requestedChange)){const audience=r.audience||r.clientType||rows.find(c=>c.id===client)?.clientType||'Cliente final',closed=r.kind==='projects'||r.dealStatus==='Pedido fechado';const budget:Entry={...(!existing?proposalDefaults(studioSettings(settings,{})):{}),...(existing||{}),id:existing?.id||'proposal-'+r.id+'-'+workKey(name),kind:'budgets',title:existing?.title||name,projectName:name,sourceRecord:r.id,serviceType:r.serviceType||existing?.serviceType||'',client,project:r.kind==='projects'?r.id:existing?.project||'',value:Number(r.value),audience,status:closed?'Aprovado':existing?.status||'Rascunho',date:existing?.date||date,startDate:existing?.startDate||r.startDate||date,firstDue:existing?.firstDue||r.firstDue||date,installments:r.paymentPlan?.length||existing?.installments||r.installments||1,paymentScheduleMode:r.paymentPlan?.length?'Parcelas mensais':existing?.paymentScheduleMode||(Number(r.installments)>1?'Parcelas mensais':'Por etapas'),payment:existing?.payment||r.payment||'',paymentMethod:r.paymentMethod||'A definir',demandStatus:r.demandStatus||r.workflowStatus,processSnapshot:existing?.processSnapshot||structuredClone(processes.find((p:any)=>p.audience===audience)||null),presentation:existing?.presentation||settings?.documentDefaults?.presentation||'slides'};if(r.kind==='clients')r.initialBudgetId=budget.id;put(budget);}}}
for(const p of related.filter(x=>x.kind==='projects'&&Number(x.value)>0)){if(!rows.some(b=>b.kind==='budgets'&&b.project===p.id&&!b.deleted)){put({id:'proposal-'+p.id+'-'+workKey(p.title),kind:'budgets',title:p.title,client:p.client,project:p.id,value:p.value,audience:p.audience||'Cliente final',status:'Aprovado',date,startDate:p.startDate||date,processSnapshot:p.processSnapshot||null,presentation:'slides'});}}
if(['contracts','agenda'].includes(r.kind)&&r.client&&!r.project){const candidates=rows.filter(p=>p.kind==='projects'&&p.client===r.client&&!p.deleted&&!p.archived);const exact=matchingProject(r.client,projectName(r),rows);if(exact||candidates.length===1)r.project=(exact||candidates[0])!.id;}
rows.splice(0,rows.length,...rows.filter(x=>x.id!==r.id),r);
for(const b of [r,...related].filter(x=>x.kind==='budgets'&&(x.status==='Aprovado'||x.status==='Pedido fechado')&&!x.integration?.completed&&!x.deleted)){const result=buildBudgetIntegration(b,rows,date);if(b.id===r.id)r=result.budget;else put(result.budget);for(const g of result.generated){if(g.id===r.id)r={...r,...g};else put(g);}}

if(['clients','projects'].includes(r.kind)){
 const budget=r.kind==='projects'?rows.find(b=>b.kind==='budgets'&&b.project===r.id&&!b.deleted):rows.find(b=>b.id===r.initialBudgetId)||rows.find(b=>b.kind==='budgets'&&b.sourceRecord===r.id&&!b.deleted),projectId=r.kind==='projects'?r.id:budget?.project,project=rows.find(p=>p.id===projectId&&p.kind==='projects');
 if(project&&r.demandStatus&&project.workflowStatus!==r.demandStatus&&records.find(x=>x.id===r.id)?.demandStatus!==r.demandStatus)put({...project,workflowStatus:r.demandStatus,status:r.demandStatus==='Entregue'?'Concluído':project.status==='Concluído'?'Modelagem':project.status});
 if(Array.isArray(r.paymentPlan)&&JSON.stringify(r.paymentPlan)!==JSON.stringify(records.find(x=>x.id===r.id)?.paymentPlan)&&(r.kind==='projects'||r.dealStatus==='Pedido fechado')){
  const error=paymentPlanError(r.paymentPlan,Number(r.value)||0);if(error)throw Error(error);if(!projectId)throw Error('Vincule o projeto antes de registrar os pagamentos.');
  const receipts=rows.filter(p=>p.kind==='finance'&&p.type==='Receita'&&!p.deleted&&p.project===projectId).sort((a,b)=>Number(a.installment||0)-Number(b.installment||0)),used=new Set<string>();
  r.paymentPlan=r.paymentPlan.map((p:any,i:number)=>{const prior=p.financeId?receipts.find(x=>x.id===p.financeId):receipts[i];if(p.financeId&&prior&&p.financeRevision!==undefined&&Number(p.financeRevision)!==Number(prior.revision||0))throw Error('Uma parcela foi atualizada enquanto você editava. Reabra o cadastro para preservar os pagamentos.');if(p.financeId&&!prior)throw Error('Uma parcela mudou. Reabra o cadastro para atualizar os pagamentos.');const id=prior?.id||'payment-'+r.id+'-'+p.id;if(used.has(id))throw Error('Confira as parcelas duplicadas.');used.add(id);const next:Entry={...prior,id,kind:'finance',title:prior?.title||projectName(project||r)+' · parcela '+(i+1)+'/'+r.paymentPlan.length,type:'Receita',client:r.kind==='clients'?r.id:r.client,project:projectId,budget:budget?.id||prior?.budget,value:Number(p.value),date:p.date||'',paidDate:p.status==='Pago'?p.paidDate:'',status:p.status,installment:i+1,installments:r.paymentPlan.length,payment:prior?.payment||r.paymentMethod||'A definir',category:prior?.category||'Projeto',paymentTrigger:prior?.paymentTrigger||'Data combinada'};const changed=!prior||Object.keys(next).some(k=>JSON.stringify(next[k])!==JSON.stringify(prior[k]));if(changed)put(next);return {...p,financeId:id,financeRevision:Number(prior?.revision||0)+(related.some(x=>x.id===id)?1:0)};});
  if(receipts.some(p=>!used.has(p.id)))throw Error('Preserve as parcelas existentes. Reabra o cadastro para conferir a quantidade.');r.installments=r.paymentPlan.length;
 }
}
if(r.kind==='finance'&&r.type==='Receita'&&r.scope!=='personal'){
 const feeId='card-fee-'+r.id,existingFee=rows.find(x=>x.id===feeId),rate=Number(r.cardFeeRate??settings?.documentDefaults?.cardFee)||0,isCard=/cart[aã]o/i.test(String(r.paymentMethod||r.payment||''));
 if(r.status==='Pago'&&isCard&&rate>0){const fee:Entry={...existingFee,id:feeId,kind:'finance',title:'Taxa do cartão · '+r.title,client:r.client||'',project:r.project||'',type:'Despesa',category:'Taxas',status:'Pago',date:r.paidDate||r.date,paidDate:r.paidDate||r.date,value:Math.round(Number(r.value)*rate)/100,sourcePayment:r.id,cardFeeRate:rate,deleted:false};if(!existingFee||Object.keys(fee).some(key=>JSON.stringify(fee[key])!==JSON.stringify(existingFee[key])))put(fee);r.cardFeeRate=rate;}
 else if(existingFee&&!existingFee.deleted)put({...existingFee,deleted:true});
}
return {record:r,related:related.filter(x=>x.id!==r.id)};}
