import {Entry} from './studio-types';
export type WorkStep={id:string;title:string;description:string;includes:string;days:number;dayType:'úteis'|'corridos';payment:number};
export type WorkProcess={id:string;audience:string;name:string;summary:string;steps:WorkStep[]};
const step=(title:string,description:string,includes:string,days:number,payment:number):WorkStep=>({id:crypto.randomUUID(),title,description,includes,days,dayType:'úteis',payment});
export function defaultProcesses():WorkProcess[]{return [
{id:'interiores',audience:'Cliente final',name:'Projeto de interiores',summary:'Do briefing ao detalhamento, com aprovação em cada fase.',steps:[step('Levantamento e briefing','Alinhar necessidades, rotina, investimento e condições do imóvel.','Briefing por ambiente\nReunião de alinhamento\nConferência das medidas',5,30),step('Estudo de layout','Definir a distribuição dos ambientes e a circulação.','Planta de layout\nOpções acordadas\nAprovação do layout',10,20),step('Anteprojeto','Apresentar materiais, volumes e a proposta visual.','Modelagem 3D\nImagens previstas no escopo\nReunião de apresentação',20,25),step('Projeto executivo','Detalhar as soluções aprovadas para orientar a execução.','Marcenaria e marmoraria contratadas\nIluminação e forro previstos\nCaderno de detalhamento',20,25),step('Entrega e acompanhamento','Entregar os arquivos finais e alinhar a execução contratada.','Conferência dos documentos\nEntrega final\nAcompanhamento somente se contratado',5,0)]},
{id:'arquitetura',audience:'Cliente final',name:'Projeto arquitetônico',summary:'Estudo, desenvolvimento e documentação conforme o escopo contratado.',steps:[step('Programa e levantamento','Definir necessidades e reunir a documentação.','Programa de necessidades\nLevantamento\nDocumentação do imóvel',7,30),step('Estudo preliminar','Definir implantação e organização do projeto.','Estudo de implantação\nLayout\nAprovação',15,20),step('Anteprojeto','Desenvolver a solução aprovada.','Plantas\nCortes e fachadas\nRevisão',20,25),step('Documentação e entrega','Organizar os desenhos e arquivos previstos.','Documentação contratada\nConferência\nEntrega',20,25)]},
{id:'online',audience:'Cliente final',name:'Consultoria online',summary:'Orientações práticas de interiores à distância.',steps:[step('Briefing e reunião','Compreender o ambiente e os objetivos.','Questionário\nFotos e medidas fornecidas\nReunião online',3,50),step('Proposta e entrega','Organizar as recomendações para o ambiente.','Layout orientativo\nPaleta e referências\nCaderno de consultoria',10,50)]},
{id:'regularizacao',audience:'Cliente final',name:'Regularização de imóvel',summary:'Análise e documentação conforme viabilidade e atribuições profissionais.',steps:[step('Análise documental','Avaliar documentos e requisitos do caso.','Documentos do imóvel\nLevantamento\nAnálise de viabilidade',10,40),step('Preparação documental','Preparar os documentos previstos no serviço.','Desenhos contratados\nConferência documental',20,40),step('Protocolo e acompanhamento','Acompanhar o procedimento contratado. Prazos do órgão são externos.','Protocolo se contratado\nAcompanhamento\nEntrega dos registros',5,20)]},
{id:'freela',audience:'Freelancer',name:'Modelagem, render e caderno',summary:'Produção técnica para escritório parceiro, com entregas e revisões definidas.',steps:[step('Arquivos e alinhamento','Conferir os arquivos e o escopo antes da produção.','Arquivos de base\nBriefing\nCenas e formatos combinados',2,50),step('Produção e prévia','Desenvolver a modelagem e as imagens contratadas.','Modelagem\nRenderizações previstas\nPrévia para aprovação',20,0),step('Ajustes e entrega','Consolidar as revisões e entregar os arquivos acordados.','Rodadas contratadas\nCaderno se contratado\nArquivos finais acordados',10,50)]},
{id:'estudante',audience:'Estudante',name:'Apoio à representação',summary:'Apoio técnico à representação de projeto desenvolvido pelo estudante.',steps:[step('Alinhamento e arquivos','Definir os materiais de base e as entregas.','Arquivos do estudante\nEscopo\nReferências',2,50),step('Produção','Produzir a representação contratada.','Modelagem ou imagens\nPrévia',10,0),step('Revisão e entrega','Conferir e entregar os arquivos combinados.','Revisão prevista\nEntrega final',3,50)]}
];}
export function processError(process:WorkProcess){if(!process||typeof process.name!=='string'||!Array.isArray(process.steps)||!process.name.trim()||!process.steps.length)return 'Preencha o nome e inclua ao menos uma etapa.';if(process.steps.some(s=>!s||typeof s.title!=='string'||!s.title.trim()||!Number.isInteger(s.days)||s.days<0||s.days>3650||!Number.isFinite(s.payment)||s.payment<0||s.payment>100||!['úteis','corridos'].includes(s.dayType)))return 'Confira nomes, prazos e pagamentos das etapas.';if(Math.abs(process.steps.reduce((a,s)=>a+s.payment,0)-100)>0.001)return 'A divisão do pagamento deve somar 100%.';return null;}
export function addWorkDays(date:string,count:number,business:boolean){const d=new Date(date+'T12:00:00Z');let left=count;while(left>0){d.setUTCDate(d.getUTCDate()+1);if(!business||![0,6].includes(d.getUTCDay()))left--;}return d.toISOString().slice(0,10);}
export function scheduledSteps(steps:WorkStep[],start:string){let cursor=start;return steps.map(s=>{const begin=cursor;cursor=addWorkDays(cursor,s.days,s.dayType==='úteis');return {...s,startDate:begin,deadline:cursor,status:'A iniciar' as const};});}
export function stagePayments(steps:ReturnType<typeof scheduledSteps>,value:number){const total=Math.round(value*100),charged=steps.filter(s=>s.payment>0),cents=charged.map(s=>Math.floor(total*s.payment/100));let remainder=total-cents.reduce((a,n)=>a+n,0);const order=charged.map((s,i)=>({i,fraction:total*s.payment/100-cents[i]})).sort((a,b)=>b.fraction-a.fraction||a.i-b.i);for(let n=0;remainder>0&&order.length;n++,remainder--)cents[order[n%order.length].i]++;return charged.map((s,i)=>({value:cents[i]/100,date:s.startDate,stage:s.id,title:s.title,percentage:s.payment}));}
export function linkedPerson(record:Entry,rows:Entry[]){return rows.find(r=>r.kind==='clients'&&r.id===(record.kind==='clients'?record.id:record.client||rows.find(p=>p.id===record.project)?.client))||rows.find(p=>p.kind==='projects'&&p.id===record.project)||record;}
export function financeSituation(r:Entry,today:string){return r.status==='Pago'?'Pago':r.status==='Em dia'?'Em dia':r.status==='Atrasado'||r.date&&r.date<today?'Atrasado':r.date?'Em dia':'Em aberto';}
