import {Entry} from './studio-types';
const finished=(r:Entry)=>['Concluído','Entregue','Finalizado'].includes(r.status)||r.workflowStatus==='Entregue';
/** History is preserved; finance stays in the ledger, but not in the active routine. */
export function clientInHistory(client:Entry,rows:Entry[]){if(client.archived)return true;const projects=rows.filter(p=>p.kind==='projects'&&p.client===client.id&&!p.deleted),quotes=rows.filter(b=>b.kind==='budgets'&&b.client===client.id&&!b.deleted&&!b.archived&&!b.integration?.completed&&['Rascunho','Enviado'].includes(b.status));return projects.length>0&&projects.every(p=>p.archived||finished(p))&&!quotes.length;}
export function routineArchived(r:Entry,rows:Entry[]){if(r.archived)return true;if(r.kind==='clients')return clientInHistory(r,rows);if(r.kind==='projects'&&finished(r))return true;const p=rows.find(p=>p.kind==='projects'&&p.id===r.project),c=rows.find(c=>c.kind==='clients'&&c.id===(r.client||p?.client));return !!(p&&(p.archived||finished(p))||c&&clientInHistory(c,rows));}
export function recordArchived(r:Entry,rows:Entry[]){return r.kind==='finance'?!!r.archived:routineArchived(r,rows);}
export function activeRoutine(rows:Entry[]){return rows.filter(r=>!r.deleted&&!routineArchived(r,rows));}
export function archiveCompletedFlow(record:Entry,related:Entry[],previous:Entry[],date:string){const all=[...previous.filter(r=>r.id!==record.id&&!related.some(x=>x.id===r.id)),record,...related],changes=new Map(related.map(r=>[r.id,r]));let root=record;for(const p of all.filter(p=>p.kind==='projects'&&!p.deleted)){
 const old=previous.find(x=>x.id===p.id);if(finished(p)){const next={...p,archived:true,archiveReason:p.archiveReason||'completed',completedDate:p.completedDate||date};if(!p.archived||!p.completedDate){if(p.id===root.id)root=next;else changes.set(p.id,next);}for(const child of all.filter(r=>r.project===p.id&&!r.deleted&&!r.archived&&['tasks','agenda'].includes(r.kind)))changes.set(child.id,{...child,archived:true,archiveReason:'project-completed',archivedByProject:p.id});}
 else if(old?.archiveReason==='completed'&&!p.archived){for(const child of all.filter(r=>r.archivedByProject===p.id&&r.archiveReason==='project-completed'))changes.set(child.id,{...child,archived:false,archiveReason:'',archivedByProject:''});}
 }return {record:root,related:[...changes.values()].filter(r=>r.id!==root.id)};}
