import {Stage} from './studio-types';
export type TrackerItem={id:string;title:string;done:boolean;notes?:string;deadline?:string};
export type TrackerRoom={id:string;title:string;items:TrackerItem[];notes?:string;sourceRoomId?:string};
export type TrackerSection={id:string;key?:string;title:string;tips:string;rooms:TrackerRoom[];done?:boolean;completedAt?:string;deadline?:string};
export type TrackerData={version:2;briefing:string;briefingChannel?:string;photos:any[];sections:TrackerSection[]};
const id=()=>crypto.randomUUID();
export const trackerItems=(names:string[])=>names.map(title=>({id:id(),title,done:false}));
function section(key:string,title:string,items:string[]=[],tips=''):TrackerSection{return {id:id(),key,title,tips,rooms:items.length?[{id:id(),title:'Checklist da etapa',items:trackerItems(items)}]:[]};}
export function freshTracker():TrackerData{return {version:2,briefing:'',briefingChannel:'',photos:[],sections:[section('briefing','Análise de briefing'),section('layout','Estudo de layout',['Conferir medidas e necessidades','Estudar distribuição e circulação','Revisar o layout com o briefing']),section('materials','Estudo de materiais',['Organizar referências e paleta','Conferir pisos e revestimentos','Definir materiais acordados']),section('modeling','Modelagem',[],'Conferir rodapés, iluminação, materiais e medidas.'),section('presentation','Montagem de apresentação',['Capa','Conferência de dados','Conferência de renderização','Conferência de layout','Conferência de todas as entregas']),section('executive','Executivo')]};}
export function sectionKey(title:string){const t=title.toLocaleLowerCase('pt-BR');return /briefing|ambientes|levantamento|alinhamento|arquivos/.test(t)?'briefing':/layout/.test(t)?'layout':/materia/.test(t)?'materials':/modelagem|produção|anteprojeto/.test(t)?'modeling':/apresenta/.test(t)?'presentation':/executivo|detalhamento|caderno/.test(t)?'executive':undefined;}
export function normalizeTracker(source:any,roomsText=''):TrackerData{
 if(!source){const data=freshTracker();const brief=data.sections[0];brief.rooms=roomsText.split(/[\n,;]+/).map(t=>t.trim()).filter(Boolean).map(title=>({id:id(),title,items:[]}));return syncTrackerRooms(data);}
 const {pendingLines,...saved}=source;const data:TrackerData={...saved,version:2,briefing:source.briefing||'',photos:source.photos||[],sections:(source.sections||[]).map((s:any)=>({...s,key:s.key||sectionKey(s.title||''),tips:s.tips||'',rooms:(s.rooms||[]).map((r:any)=>({...r,items:r.items||[]}))}))};
 if(source.version!==2){const fresh=freshTracker();if(!data.sections.some(s=>s.key==='briefing'))data.sections.unshift(fresh.sections[0]);const brief=data.sections.find(s=>s.key==='briefing')!;if(brief.title==='Ambientes')brief.title='Análise de briefing';for(const key of ['layout','materials'])if(!data.sections.some(s=>s.key===key)){const position=data.sections.findIndex(s=>s.key==='modeling');data.sections.splice(position<0?data.sections.length:position,0,fresh.sections.find(s=>s.key===key)!);}for(const key of ['modeling','presentation','executive'])if(!data.sections.some(s=>s.key===key))data.sections.push(fresh.sections.find(s=>s.key===key)!);const presentation=data.sections.find(s=>s.key==='presentation')!;if(!presentation.rooms.length)presentation.rooms=fresh.sections.find(s=>s.key==='presentation')!.rooms;}
 return syncTrackerRooms(data);
}
/** Mirror room identity/name only; never copy or erase checklist completion/notes. */
export function syncTrackerRooms(data:TrackerData):TrackerData{const brief=data.sections.find(s=>s.key==='briefing'),model=data.sections.find(s=>s.key==='modeling');if(!brief||!model)return data;let rooms=model.rooms.map(r=>r.sourceRoomId&&!brief.rooms.some(b=>b.id===r.sourceRoomId)?{...r,sourceRoomId:undefined}:r);for(const b of brief.rooms){let existing=rooms.find(r=>r.sourceRoomId===b.id)||rooms.find(r=>!r.sourceRoomId&&r.title.trim().toLocaleLowerCase()===b.title.trim().toLocaleLowerCase());if(existing)rooms=rooms.map(r=>r.id===existing!.id?{...r,title:b.title,sourceRoomId:b.id}:r);else rooms.push({id:id(),sourceRoomId:b.id,title:b.title,items:[]});}return {...data,sections:data.sections.map(s=>s.id===model.id?{...s,rooms}:s)};}
export function trackerProgress(s:TrackerSection){const items=s.rooms.flatMap(r=>r.items),done=items.filter(i=>i.done).length,completed=items.length>0?done===items.length:!!s.done;return {items,done,completed,percent:items.length?Math.round(done/items.length*100):completed?100:0};}
export function completeTrackerSection(s:TrackerSection,done:boolean):TrackerSection{return {...s,done,rooms:s.rooms.map(r=>({...r,items:r.items.map(i=>({...i,done}))})),completedAt:done?new Date().toISOString():''};}
export function trackerStageSnapshot(data:TrackerData,previous:Stage[]=[]):Stage[]{const used=new Set<string>();const snapshots=data.sections.map(s=>{const prior=previous.find(p=>p.id===s.id)||previous.find(p=>!used.has(p.id)&&sectionKey(p.title)===s.key&&s.key);if(prior)used.add(prior.id);const progress=trackerProgress(s);return {...prior,id:prior?.id||s.id,title:s.title,status:progress.completed?'Concluída' as const:progress.done||s.rooms.some(r=>r.items.length)||s.key==='briefing'&&data.briefing?'Em andamento' as const:'A iniciar' as const,deadline:s.deadline||prior?.deadline||''};});return [...snapshots,...previous.filter(p=>!used.has(p.id)&&!data.sections.some(s=>s.id===p.id))];}
