'use client';
import {useMoney,useMoneyVisibility,HiddenValues} from './money-privacy';
import {RecordMessages} from './message-scripts';
import {Entry,formatDay} from '@/lib/studio-types';
import {budgetTotal,documentSections} from '@/lib/document-content';
import {PdfPreview} from '@/components/studio/pdf-preview';
import {downloadPDF} from '@/lib/pdf-document';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {toast} from 'sonner';
export function BudgetDetails({record,rows,settings,onEdit,onBack,onOpen,onPersist,saving}:{record:Entry;rows:Entry[];settings:any;onEdit:(r:Entry)=>void;onBack:()=>void;onOpen:(r:Entry)=>void;onPersist:(r:Entry)=>Promise<boolean>;saving:boolean}){const formatMoney=useMoney(),{visible:moneyVisible}=useMoneyVisibility();const client=rows.find(r=>r.id===record.client),project=rows.find(r=>r.id===record.project),finance=rows.filter(r=>r.kind==='finance'&&!r.deleted&&!r.archived&&(r.budget===record.id||project&&r.project===project.id)),paid=finance.filter(r=>r.type==='Receita'&&r.status==='Pago').reduce((a,r)=>a+Number(r.value||0),0);return <div className="reference-view"><button className="text-button" onClick={onBack}>Voltar aos orçamentos</button><div className="reference-heading"><div><h1>{record.title}</h1><button className="text-button" onClick={()=>client&&onOpen(client)}>{client?.title||'Cliente a vincular'}</button></div><div className="actions"><button className="button" onClick={()=>onEdit(record)}>Editar proposta</button><button className="button" disabled={record.allowPDF===false} onClick={()=>downloadPDF(record,rows,settings).catch(e=>toast.error(e.message))}>PDF</button>{!record.integration?.completed&&<button className="button primary" disabled={saving||!record.client||!!record.deleted} onClick={()=>onPersist({...record,status:'Aprovado'})}>Pedido fechado</button>}{project&&<button className="button" onClick={()=>onOpen(project)}>Abrir demanda</button>}</div></div><RecordMessages record={record} rows={rows} settings={settings}/><div className="finance-kpis"><div className="finance-kpi"><span>Valor acordado</span><strong>{formatMoney(budgetTotal(record))}</strong></div><div className="finance-kpi"><span>Recebido</span><strong>{formatMoney(paid)}</strong></div><div className="finance-kpi"><span>{record.integration?.completed?'A receber':'Valor em proposta'}</span><strong>{formatMoney(Math.max(0,budgetTotal(record)-paid))}</strong></div><div className="finance-kpi"><span>Situação</span><strong className="budget-status">{record.status==='Aprovado'?'Pedido fechado':record.status}</strong><small>Validade: {formatDay(record.validity)}</small></div></div><Tabs defaultValue="agreement"><TabsList><TabsTrigger value="agreement">Valores e condições</TabsTrigger><TabsTrigger value="preview">Prévia da proposta</TabsTrigger></TabsList><TabsContent value="agreement"><section className="panel budget-agreement">{documentSections(record,rows,settings).map((s,i)=><section key={i}><h3>{s.title}</h3><p>{s.body}</p></section>)}</section></TabsContent><TabsContent value="preview"><PdfPreview entry={record} rows={rows} settings={settings}/></TabsContent></Tabs></div>}
