'use client';
import {useState} from 'react';
import {Entry,formatDay} from '@/lib/studio-types';
import {clientPanelData,panelGroups} from '@/lib/client-panel-data';
import {workflow} from '@/lib/operations-data';
import {budgetTotal} from '@/lib/document-content';
import {documentSections} from '@/lib/document-content';
import {useMoney,useMoneyVisibility} from './money-privacy';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Search,ChevronLeft} from 'lucide-react';
export function ClientPanels({rows,onPersist,onOpen,settings={}}:{rows:Entry[];onPersist:(r:Entry)=>Promise<boolean>;onOpen:(r:Entry)=>void;settings?:any}){const [search,setSearch]=useState(''),[selected,setSelected]=useState(''),money=useMoney(),{visible}=useMoneyVisibility(),groups=panelGroups(rows),unlinked=rows.filter(r=>r.kind==='budgets'&&!r.deleted&&!rows.some(c=>c.kind==='clients'&&c.id===r.client&&!c.deleted)),current=rows.find(c=>c.id===selected&&c.kind==='clients'&&!c.deleted),data=current?clientPanelData(current,rows):null;
 const budgetCard=(b:Entry)=><section className="panel panel-budget" key={b.id}><div className="section-head"><button className="record-name" onClick={()=>onOpen(b)}>{b.title}</button><span className="tag">{b.integration?.completed||b.status==='Aprovado'?'Pedido fechado':b.status}</span><b>{money(budgetTotal(b))}</b></div><small>Proposta #{b.number||'—'} · {formatDay(b.date)} · {b.audience||'Cliente final'}</small><details><summary>Ver escopo, entregas e condições</summary>{documentSections(b,rows,settings).map((s,i)=><div className="detail-text" key={i}><h3>{s.title}</h3><p>{visible?s.body:s.body.replace(/R\$[\s\u00a0]*[\d.,]+/g,'••••')}</p></div>)}</details><div className="actions"><button className="button" onClick={()=>onOpen(b)}>Abrir orçamento</button>{b.project&&rows.some(p=>p.id===b.project&&!p.deleted)&&<button className="button" onClick={()=>onOpen(rows.find(p=>p.id===b.project)!)}>Abrir demanda</button>}</div></section>;
 if(current&&data)return <div className="reference-view"><button className="text-button" onClick={()=>setSelected('')}><ChevronLeft size={15}/>Todos os clientes</button><div className="reference-heading"><div><p className="eyebrow">PAINEL PRIVADO DO CLIENTE</p><h1>{current.title}</h1><p className="muted">{current.email||current.phone||''}</p></div><button className="button" onClick={()=>onOpen(current)}>Abrir cadastro</button></div><div className="finance-kpis">{[['Recebido',money(data.paid)],['A receber',money(data.pending)],['Em atraso',money(data.overdue)],['Próxima entrega',formatDay(data.deadline)]].map(([label,value])=><div className="finance-kpi" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><Tabs defaultValue="budgets"><TabsList className="detail-tabs">{[['budgets','Orçamentos'],['projects','Etapas e projetos'],['contracts','Contratos'],['briefings','Briefings'],['documents','Documentos'],['finance','Pagamentos'],['tasks','Demandas']].map(([v,l])=><TabsTrigger key={v} value={v}>{l}</TabsTrigger>)}</TabsList><TabsContent value="budgets"><h2>orçamentos em aberto</h2>{data.openBudgets.map(budgetCard)}{!data.openBudgets.length&&<p className="quiet-empty">Nenhum orçamento em aberto.</p>}<details className="panel closed-history"><summary>Projetos fechados e histórico · {data.historyBudgets.length}</summary>{data.historyBudgets.map(budgetCard)}{!data.historyBudgets.length&&<p className="quiet-empty">Nenhum orçamento no histórico.</p>}</details></TabsContent><TabsContent value="projects">{data.projects.map(p=><section className="panel" key={p.id}><div className="section-head"><button className="record-name" onClick={()=>onOpen(p)}>{p.title}</button><span className="tag">{workflow(p)}</span></div><p className="record-subtitle">Entrega: {formatDay(p.deadline)}</p><ol className="client-stage-list">{(p.stages||[]).map(s=><li key={s.id}><span className={s.status==='Concluída'?'finished':''}/><div><b>{s.title}</b><small>{s.status}{s.deadline?' · '+formatDay(s.deadline):''}</small>{s.description&&<p>{s.description}</p>}{s.includes&&<small>{s.includes}</small>}</div></li>)}</ol></section>)}</TabsContent>{['contracts','briefings','documents','finance','tasks'].map(kind=><TabsContent key={kind} value={kind}><section className="panel">{data.related.filter(r=>r.kind===kind).map(r=><div className="project-line" key={r.id}><button className="record-name" onClick={()=>onOpen(r)}>{r.title}<small>{rows.find(p=>p.id===r.project)?.title}</small></button><span className="tag">{r.status}</span>{kind==='finance'?<b>{money(r.value)}</b>:<span>{formatDay(r.deadline||r.date)}</span>}</div>)}{!data.related.some(r=>r.kind===kind)&&<p className="quiet-empty">Nenhum registro vinculado.</p>}</section></TabsContent>)}</Tabs></div>;
 const accepts=(c:Entry)=>{const d=clientPanelData(c,rows);return [c.title,...d.budgets.map(b=>b.title),...d.projects.map(p=>p.title)].join(' ').toLocaleLowerCase().includes(search.toLocaleLowerCase())};const card=(c:Entry)=>{const d=clientPanelData(c,rows);return <article className="client-panel-card" key={c.id}><div className="client-card-header"><span className="client-initial">{c.title.slice(0,1).toUpperCase()}</span><div><b>{c.title}</b><small>{c.clientType||'Cliente final'} · {d.budgets.length} orçamento(s)</small></div></div><div className="client-stage"><b>{d.openBudgets.length?d.openBudgets.length+' proposta(s) em aberto':d.current?workflow(d.current):'Histórico de projetos'}</b></div><div className="client-mini-stats"><div><small>RECEBIDO</small><b>{money(d.paid)}</b></div><div><small>A RECEBER</small><b>{money(d.pending)}</b></div></div><button className="button" onClick={()=>setSelected(c.id)}>Abrir painel do cliente</button></article>};return <div className="reference-view"><div className="reference-heading"><div><p className="eyebrow">CLIENTES E PROPOSTAS</p><h1>painel <em>do cliente</em></h1><p className="muted">Orçamentos vinculados aparecem automaticamente. Pedidos fechados ficam no histórico e continuam nas demandas e no financeiro.</p></div></div><label className="search client-panel-search"><Search size={14}/><input placeholder="Buscar cliente ou orçamento…" value={search} onChange={e=>setSearch(e.target.value)}/></label><p className="group-caption">ORÇAMENTOS EM ABERTO</p><div className="client-panel-grid">{groups.open.filter(accepts).map(card)}</div>{!groups.open.some(accepts)&&<p className="quiet-empty">Nenhum orçamento em aberto nesta busca.</p>}{unlinked.length>0&&<details className="panel closed-history"><summary>Orçamentos sem cliente vinculado · {unlinked.length}</summary><p className="settings-note">Abra a proposta e vincule o cliente para reunir as informações no painel dele.</p>{unlinked.map(budgetCard)}</details>}<details className="panel closed-history"><summary>Projetos fechados e histórico · {groups.history.filter(accepts).length}</summary><div className="client-panel-grid">{groups.history.filter(accepts).map(card)}</div></details>{groups.other.some(accepts)&&<details className="panel closed-history"><summary>Outros clientes cadastrados · {groups.other.filter(accepts).length}</summary><div className="client-panel-grid">{groups.other.filter(accepts).map(card)}</div></details>}</div>;
}
