'use client';
import {useMoney,useMoneyVisibility,HiddenValues} from './money-privacy';
import {useEffect,useRef} from 'react';
import {Entry} from '@/lib/studio-types';
import {draftPaymentPlan,linkedReceipts,PaymentPlanRow} from '@/lib/payment-plan';
import {installmentPlan} from '@/lib/installments';
import {financeSituation} from '@/lib/work-processes';
import {localDay} from '@/lib/operations-data';
export function ClientPaymentPlan({record,rows,onChange}:{record:Entry;rows:Entry[];onChange:(key:string,value:any)=>void}){const formatMoney=useMoney(),{visible:moneyVisible}=useMoneyVisibility();
 const previous=useRef(''),receipts=linkedReceipts(record,rows),count=Math.min(60,Math.max(1,Number(record.installments)||receipts.length||1));
 useEffect(()=>{const signature=record.id+'|'+count+'|'+record.value+'|'+record.firstDue;if(previous.current===signature)return;const first=!previous.current;previous.current=signature;let plan:PaymentPlanRow[]=first&&receipts.length?draftPaymentPlan({...record,paymentPlan:undefined},rows):record.paymentPlan||draftPaymentPlan(record,rows);const initial=!record.paymentPlan||first&&receipts.length>0;
 if(!initial){if(plan.length<count){const cents=Math.round(Number(record.value)*100)-Math.round(plan.reduce((a,p)=>a+p.value,0)*100),newCount=count-plan.length;const added=installmentPlan(Math.max(0,cents)/100,newCount,record.firstDue||'2000-01-01').map((p,i)=>({id:crypto.randomUUID(),...p,date:record.firstDue?p.date:'',paidDate:'',status:'Em dia'}));plan=[...plan,...added];}else if(plan.length>count){const removed=plan.slice(count);if(!removed.some(p=>p.financeId||p.status==='Pago'||p.paidDate))plan=plan.slice(0,count);}if(plan.every(p=>!p.manualValue&&!p.financeId&&!p.paidDate)){const fresh=draftPaymentPlan({...record,paymentPlan:undefined},[]);plan=fresh.map((p,i)=>({...p,id:plan[i]?.id||p.id}));}}
 if(JSON.stringify(plan)!==JSON.stringify(record.paymentPlan))onChange('paymentPlan',plan);
 },[record.id,count,record.value,record.firstDue]);
 const plan:PaymentPlanRow[]=record.paymentPlan||draftPaymentPlan(record,rows),patch=(i:number,p:Partial<PaymentPlanRow>)=>onChange('paymentPlan',plan.map((row,n)=>n===i?{...row,...p}:row)),paid=plan.filter(p=>p.status==='Pago').reduce((a,p)=>a+p.value,0),late=plan.filter(p=>financeSituation({...p,kind:'finance',title:''} as Entry,localDay())==='Atrasado').reduce((a,p)=>a+p.value,0),sum=plan.reduce((a,p)=>a+p.value,0),difference=Math.round((Number(record.value)-sum)*100)/100;
 return <section className="client-payment-plan"><h3>Parcelas do valor acordado</h3><p className="settings-note">Registre pagamentos antigos com a data real. Sem data de pagamento, a parcela continua em aberto. O vencimento pode ficar vazio enquanto estiver a combinar. Ao salvar um pedido fechado, estas parcelas alimentam o financeiro.</p>{plan.length!==count&&<p role="alert">Há parcelas já registradas. Preserve-as; edite seus valores e datas em vez de reduzir a quantidade.</p>}{plan.map((p,i)=><fieldset className="item-editor" key={p.id}><legend>Parcela {i+1} de {plan.length}</legend><div className="form-grid"><label className="field"><span>Valor (R$)</span>{moneyVisible?<input type="number" min="0" step="0.01" value={p.value} onChange={e=>patch(i,{value:Number(e.target.value),manualValue:true})}/>:<span>••••</span>}</label><label className="field"><span>Vencimento · opcional</span><input type="date" value={p.date} onChange={e=>patch(i,{date:e.target.value})}/></label><label className="field"><span><input type="checkbox" checked={p.status==='Pago'} onChange={e=>patch(i,{status:e.target.checked?'Pago':'Em dia',paidDate:e.target.checked?p.paidDate:''})}/>Já foi paga</span><input type="date" aria-label={'Data do pagamento da parcela '+(i+1)} value={p.paidDate} onChange={e=>patch(i,{paidDate:e.target.value,status:e.target.value?'Pago':'Em dia'})}/></label>{p.status!=='Pago'&&<label className="field"><span>Situação da parcela aberta</span><select value={p.status} onChange={e=>patch(i,{status:e.target.value,paidDate:''})}><option value="Em dia">Em dia</option><option value="Atrasado">Em atraso</option><option value="Pendente">Automático pelo vencimento</option></select></label>}</div></fieldset>)}<div className="demand-payment-summary"><div><span>Recebido</span><b>{formatMoney(paid)}</b></div><div><span>A receber</span><b>{formatMoney(sum-paid)}</b></div><div><span>Em atraso</span><b className="late-text">{formatMoney(late)}</b></div></div>{difference!==0&&<p role="alert">Ajuste a distribuição: diferença de {formatMoney(difference)} em relação ao valor acordado.</p>}</section>;
}
