'use client';
import {useEffect,useState} from 'react';
import {Entry} from '@/lib/studio-types';
import {referenceModels,referenceAsset,applyReferenceModel,downloadReferenceWord,resolveTemplateText} from '@/lib/reference-templates';
import {toast} from 'sonner';
export function ReferenceModelCatalog(){return <div className="template-grid">{referenceModels.map(m=><article className="template-card" key={m.id}><b>{m.title}</b><p>{m.description}</p><small>Disponível no editor → Modelos dos seus arquivos</small></article>)}</div>}
export function ReferenceModels({draft,rows,settings,update}:{draft:Entry;rows:Entry[];settings:any;update:(key:string,value:any)=>void}){const [busy,setBusy]=useState(false),[model,setModel]=useState<any>(null);useEffect(()=>{let live=true;setModel(null);if(draft.referenceTemplate?.startsWith('contract-'))referenceAsset(draft.referenceTemplate).then(d=>{if(live)setModel(d)}).catch(e=>toast.error(e.message));return()=>{live=false}},[draft.referenceTemplate]);const set=(id:string)=>{setBusy(true);applyReferenceModel(id,update,draft).catch(e=>toast.error(e.message)).finally(()=>setBusy(false));};return <section className="reference-model-tools"><h3>Modelos dos seus arquivos</h3><p className="muted">Escolha o modelo. A prévia acompanha os textos e valores deste documento.</p><div className="actions">{referenceModels.filter(m=>m.kind===draft.kind).map(m=><button type="button" disabled={busy} className={'button '+(draft.referenceTemplate===m.id?'primary':'')} key={m.id} onClick={()=>set(m.id)}>{m.title}</button>)}</div>{draft.referenceTemplate&&<button className="text-button" type="button" onClick={()=>{update('referenceTemplate','');update('referenceParagraphs',undefined)}}>Usar layout padrão da plataforma</button>}
{model&&<><p className="muted">Os campos entre chaves acompanham os dados do cliente, do projeto e o valor do contrato. Você também pode substituir qualquer trecho por um texto próprio.</p><div className="form-grid">{[['projectAddress','Endereço do imóvel'],['rooms','Ambientes contratados'],['bankDetails','Dados bancários / PIX']].map(([key,label])=><label className="field" key={key}><span>{label}</span><input value={draft[key]||''} onChange={e=>update(key,e.target.value)}/></label>)}</div><details><summary>Editar todos os textos do contrato</summary>{model.paragraphs.filter((p:any)=>p.text&&p.role!=='brand').map((p:any)=><label className="field" key={p.index}><span>{p.text.length<65?p.text.replace(/\{\{[^}]+\}\}/g,'…'):'Texto '+(p.index+1)}</span><textarea rows={Math.min(8,Math.max(2,Math.ceil(p.text.length/80)))} value={draft.referenceParagraphs?.[p.index]??p.text} onChange={e=>update('referenceParagraphs',{...draft.referenceParagraphs,[p.index]:e.target.value})}/><small>{resolveTemplateText(draft.referenceParagraphs?.[p.index]??p.text,draft,rows,settings)}</small></label>)}</details><button type="button" className="button" disabled={busy} onClick={async()=>{setBusy(true);try{await downloadReferenceWord(draft,rows,settings)}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}}>Baixar Word com a formatação original</button></>}
{draft.referenceTemplate==='proposal-nunes'&&<><p className="muted">A capa, as imagens e a sequência de seis páginas são fixas. O nome vem do cliente vinculado; o investimento acompanha os valores do orçamento.</p>{[['referenceSubtitle','Tipo e identificação do projeto','text'],['scope','O que será entregue · um item por linha','textarea'],['rooms','Ambientes contratados','text'],['payment','Forma de pagamento','textarea'],['term','Etapas e prazos','textarea'],['referenceConditions','Condições de início e aprovação','textarea']].map(([key,label,type])=><label className="field" key={key}><span>{label}</span>{type==='textarea'?<textarea rows={5} value={draft[key]||''} onChange={e=>update(key,e.target.value)}/>:<input value={draft[key]||''} onChange={e=>update(key,e.target.value)}/>}</label>)}<label className="field"><span>Valor à vista / PIX (opcional)</span><input type="number" min="0" step="0.01" value={draft.cashValue??''} onChange={e=>update('cashValue',e.target.value===''?'':Number(e.target.value))}/></label><details><summary>Textos de apresentação</summary>{[['referenceAbout','Sobre o estúdio'],['referenceServiceTitle','Título do serviço'],['referenceService','Apresentação do serviço']].map(([key,label])=><label className="field" key={key}><span>{label}</span><textarea rows={5} value={draft[key]||''} placeholder="Manter texto do modelo" onChange={e=>update(key,e.target.value)}/></label>)}</details></>}
</section>}
