'use client';
import {useState} from 'react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
const chapters=[
['Configuração do estúdio','settings','Clique na bolinha ao lado de NUNES INTERIORES para enviar o logotipo em PNG ou JPG. Em Aparência, ajuste fontes, cores e cantos. O tema claro ou escuro é guardado por aparelho. Preencha seus dados profissionais e ajuste a identidade visual. Revise as informações usadas nos documentos antes de gerar propostas e contratos.'],
['Serviços e preços','settings','Cadastre seus valores por hora, m² ou unidade. Defina valor fixo adicional, mínimo, pacote e público. No orçamento, selecione o serviço cadastrado e informe quantidade, complexidade, urgência ou arquivo editável. Confira a sugestão antes de adicioná-la: os valores continuam editáveis e não alteram propostas existentes.'],
['Padrões de propostas','settings','Escolha slides ou folha objetiva e um dos modelos de PDF. Defina textos, pagamento, arquivos entregues, ajustes, numeração e fotos de apresentação. Os próximos orçamentos copiam esses padrões; condições já salvas são preservadas.'],
['Cadastro do cliente','clients','Cadastre nome, contato, profissão e perfil de contratação. Cliente final contrata para o próprio imóvel; freelancer ou parceiro contrata produção para outro escritório; estudante contrata apoio à representação. Você também pode cadastrar a pessoa dentro de um orçamento ou atividade. Ao informar projeto e valor no cadastro, um orçamento é criado automaticamente. Marcar Pedido fechado gera a demanda e suas parcelas. Vincule cada registro à pessoa correta.'],
['Etapas de trabalho','processes','Escolha o perfil e o processo. Defina nome, explicação, entregas, prazo em dias úteis ou corridos e percentual do pagamento por etapa. A soma deve ser 100%. Salvar atualiza somente os próximos registros; propostas existentes preservam a configuração copiada. Dias úteis excluem sábados e domingos; ajuste feriados e interrupções no cronograma.'],
['Briefing e alinhamento','briefings','Reúna rotina, necessidades, referências, medidas, orçamento e prioridades por ambiente. Confira as respostas antes da reunião. Registre decisões e pendências. A produção deve começar após receber as informações e cumprir as condições acordadas.'],
['Proposta comercial','budgets','Escolha o destinatário e o processo. Revise serviços, entregáveis, formatos dos arquivos, exclusões, rodadas de ajustes, prazo, valor e pagamento. Use slides para apresentar as etapas. Confirme a data prevista de início antes de gerar o cronograma. Não prometa entregas que dependam de informações ainda pendentes.'],
['Aprovação e contrato','contracts','Ao marcar Pedido fechado ou aprovar a proposta, projeto, contrato, parcelas e atividades são criados automaticamente, sem repetir os registros. Confira os dados das partes e a correspondência entre proposta e contrato. A integração não representa assinatura: registre o status Assinado depois da assinatura efetiva.'],
['Demandas e revisões','tasks','Cada cliente e projeto tem um cartão; as atividades do mesmo projeto ficam reunidas nele. Use o mesmo nome do projeto para manter esse vínculo. Atualize a situação do trabalho e marque as etapas concluídas. Registre solicitações de ajuste por rodada e preserve o escopo aprovado. Solicitações adicionais devem ter prazo e valor acordados antes da execução. Ao clicar no nome do cliente, você abre a ficha; ao clicar no trabalho, abre o projeto ou editor.'],
['Agenda e lembretes','agenda','Registre reuniões, visitas e entregas com data e horário. A agenda reúne compromissos, prazos e vencimentos. Clique no nome da atividade para consultar a pessoa vinculada e use Editar para alterar o registro. Lembretes da página inicial servem para retornos e conferências rápidas.'],
['Controle financeiro','finance','Consulte a aba Parcelas para acompanhar o pagamento acordado. A demanda e o financeiro usam os mesmos lançamentos: pagar em uma tela atualiza a outra. Valores em propostas aparecem separados de receitas recebidas. Registre entradas e despesas separadamente. Marque Pago apenas após confirmar o recebimento ou desembolso e confira a data do pagamento. Atrasado indica vencimento não quitado; Em dia indica parcela em aberto dentro do prazo. Uma parcela vencida permanece atrasada até pagamento ou alteração acordada do vencimento. A taxa cadastrada para cartão gera uma despesa vinculada ao recebimento pago no cartão; reabrir o recebimento retira essa despesa. O saldo mostrado é recebido menos despesas pagas, sem apuração tributária.'],
['Contratos assinados em PDF','contracts','Abra Anexos no contrato ou na ficha do cliente. Envie o PDF original e indique se já está assinado. O arquivo fica disponível para consulta e download. Ao anexar um contrato assinado pela ficha do cliente, ele também aparece em Contratos. Salve o cadastro antes de anexar.'],
['Painel do cliente e entrega','clientPanel','Use o painel privado para reunir projetos, etapas, pagamentos e documentos. Confira pendências de aprovação e arquivos antes da entrega. Entregue os formatos contratados e registre a conclusão. O painel continua restrito ao seu acesso; ativá-lo não cria um link público.'],
['Salvar, sair e preservar dados','settings','Ao sair de um editor, escolha Salvar e sair, Não salvar e sair ou Continuar editando. Descartar mantém o último registro salvo. Use a lixeira para exclusões reversíveis e exporte backups nas configurações. No modo de exemplo, alterações são temporárias e não entram nos seus dados.']
];
export function StudioManual({onGo}:{onGo:(k:any)=>void}){const [profile,setProfile]=useState('final');return <div className="reference-view"><h1>manual <em>de uso</em></h1><section className="panel"><h2>rotina de gestão · NUNES INTERIORES</h2><p>Organize as informações uma vez, acompanhe o trabalho por etapas e registre aprovações e pagamentos no momento em que acontecerem.</p><a className="button" href="/Manual-Nunes-Interiores.md" download>Baixar manual</a></section><section className="panel"><Tabs value={profile} onValueChange={setProfile}><TabsList><TabsTrigger value="final">cliente final</TabsTrigger><TabsTrigger value="partner">freelancer / parceiro</TabsTrigger><TabsTrigger value="student">estudante</TabsTrigger></TabsList></Tabs><p className="manual-path">{profile==='final'?'Briefing → reunião → proposta → contrato → cronograma → desenvolvimento → entrega':profile==='partner'?'Arquivos de base → escopo → proposta → contrato → produção → revisões → entrega':'Arquivos e objetivo → escopo de apoio → proposta → produção → revisão → entrega'}</p></section>{chapters.map(([title,route,text],i)=><details className="panel manual-chapter" key={title} open={i===0}><summary><em>{String(i+1).padStart(2,'0')}</em><b>{title}</b></summary><p>{text}</p><button className="button" onClick={()=>onGo(route)}>Abrir módulo</button></details>)}</div>}
export const manualChapters=chapters;
