import {applyTimelineUpdate} from '../lib/project-timeline';
import {Entry} from '../lib/studio-types';
import {validateRecord,historyAction,changedFields} from '../lib/record-validation';
import {prepareStudioFlow} from '../lib/studio-flow';
import {fontFormat} from '../lib/font-file';
import {installmentPlan} from '../lib/installments';
export type FirebaseConfig={apiKey:string;projectId:string;ownerUid:string;multiUserEnabled?:boolean};
export function createFirebaseBridge(config:FirebaseConfig,nativeFetch:typeof fetch){let session:any=null,resetting=false;const prefix=`projects/${config.projectId}/databases/(default)/documents`,root='https://firestore.googleapis.com/v1/'+prefix;const storageKey='nunes-firebase-session';const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'});const path=(collection:string,id?:string)=>`users/${session.uid}/${collection}${id?'/'+encodeURIComponent(id):''}`;function remember(){if(typeof sessionStorage!=='undefined')sessionStorage.setItem(storageKey,JSON.stringify(session));}function restore(){try{const s=JSON.parse(sessionStorage.getItem(storageKey)||'null');if(s?.uid&&(config.multiUserEnabled||s.uid===config.ownerUid)&&s.idToken&&s.refreshToken)session=s;}catch{}}restore();
 async function token(){if(!session||(!config.multiUserEnabled&&session.uid!==config.ownerUid))throw Error('Entre com a conta responsável pelo estúdio.');if(session.expiresAt<Date.now()+60000){const response=await nativeFetch(`https://securetoken.googleapis.com/v1/token?key=${encodeURIComponent(config.apiKey)}`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:session.refreshToken})}),data:any=await response.json();if(!response.ok)throw Error('Sua sessão expirou. Entre novamente.');if(data.user_id!==session.uid)throw Error('Acesso não autorizado.');session={...session,uid:data.user_id,idToken:data.id_token,refreshToken:data.refresh_token,expiresAt:Date.now()+Number(data.expires_in)*1000};remember();}return session.idToken;}
 async function request(url:string,init:RequestInit={}){const response=await nativeFetch(url,{...init,headers:{...init.headers,Authorization:'Bearer '+await token()}});if(!response.ok){const data:any=await response.json().catch(()=>({}));const error:any=Error(response.status===403?'Acesso não autorizado. Confira as regras e a conta do Firebase.':response.status===409||response.status===400&&data.error?.status==='FAILED_PRECONDITION'?'O registro mudou em outra tela. Recarregue antes de salvar.':data.error?.message||'Não foi possível conectar ao Firebase.');error.status=response.status;throw error;}return response;}
 async function readCollection(collection:string){let all:any[]=[],page='';do{const response=await request(root+'/'+path(collection)+'?pageSize=300'+(page?'&pageToken='+encodeURIComponent(page):'')),data:any=await response.json();all.push(...(data.documents||[]));page=data.nextPageToken||'';}while(page);return all;}
 function decode(doc:any){return {...JSON.parse(doc.fields.payload.stringValue),_updateTime:doc.updateTime};}function strip(r:any){const {_updateTime,...value}=r;return value;}
 async function records(){return (await readCollection('records')).map(decode) as Entry[];}
 function write(collection:string,id:string,payload:any,condition:any={exists:false}){return {update:{name:prefix+'/'+path(collection,id),fields:{payload:{stringValue:JSON.stringify(strip(payload))}}},currentDocument:condition};}
 async function commit(writes:any[]){if(writes.length>450)throw Error('Há muitas alterações nesta operação. Divida o cadastro em partes.');await request(root+':commit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({writes})});}
 async function save(rootEntry:Entry,related:Entry[],rows:Entry[]){const time=new Date().toISOString(),planned=[rootEntry,...related.filter(r=>r.id!==rootEntry.id)],all=[...rows.filter(r=>!planned.some(x=>x.id===r.id)),...planned];const entries=planned.map(input=>{const error=validateRecord(input);if(error)throw Error(error);const prior=rows.find(r=>r.id===input.id);if(prior&&prior.kind!==input.kind)throw Error('Identificador de outro módulo.');if((input.revision||0)!==(prior?.revision||0))throw Error('O registro mudou em outra tela. Recarregue antes de salvar.');for(const [field,kind] of [['client','clients'],['project','projects']])if(input[field]){const linked=all.find(r=>r.id===input[field]&&r.kind===kind);if(!linked||linked.deleted&&prior?.[field]!==input[field])throw Error('Confira o cliente e projeto vinculados.');if(field==='project'&&linked.client&&input.client&&input.client!==linked.client)throw Error('O cliente não corresponde ao projeto.');}return {...strip(input),revision:(prior?.revision||0)+1,mutationId:crypto.randomUUID(),createdAt:prior?.createdAt||time,updatedAt:time};});const writes:any[]=[];entries.forEach(r=>{const prior=rows.find(x=>x.id===r.id);writes.push(write('records',r.id,r,prior?{updateTime:prior._updateTime}:{exists:false}));const id=crypto.randomUUID();writes.push(write('versions',id,{id,recordId:r.id,record:r,createdAt:time}));writes.push(write('history',id,{id,recordId:r.id,client:r.client||'',project:r.project||'',kind:r.kind,title:r.title,action:historyAction(prior||null,r),changed:changedFields(prior||null,r),createdAt:time}));});await commit(writes);return {record:entries[0],records:[...entries,...rows.filter(r=>!entries.some(x=>x.id===r.id)).map(strip)]};}
 async function saveInput(input:Entry){const rows=await records(),prior=rows.find(r=>r.id===input.id);if((input.revision||0)!==(prior?.revision||0))throw Error('O registro mudou em outra tela. Recarregue antes de salvar.');const flow=prepareStudioFlow(input,rows,today());return save(flow.record,flow.related,rows);}
 async function readFile(key:string){const response=await request(root+'/'+path('files',key)),meta=decode(await response.json());const docs=await readCollection('files/'+encodeURIComponent(key)+'/chunks'),chunks=docs.map(decode).sort((a,b)=>a.index-b.index);if(chunks.length!==meta.chunks)throw Error('Arquivo incompleto.');const parts=chunks.map(c=>Uint8Array.from(atob(c.bytes),(c:string)=>c.charCodeAt(0)));return new Blob(parts,{type:meta.mime});}
 async function removeFile(key:string){const docs=await readCollection('files/'+encodeURIComponent(key)+'/chunks');const deletes=docs.map(d=>({delete:d.name}));deletes.push({delete:prefix+'/'+path('files',key)});await commit(deletes);}
 async function uploadFile(file:File){const key=crypto.randomUUID(),bytes=new Uint8Array(await file.arrayBuffer()),writes:any[]=[];for(let offset=0,index=0;offset<bytes.length;offset+=64000,index++){let raw='';for(const b of bytes.subarray(offset,offset+64000))raw+=String.fromCharCode(b);writes.push(write('files/'+key+'/chunks',String(index),{index,bytes:btoa(raw)}));}try{for(let i=0;i<writes.length;i+=20)await commit(writes.slice(i,i+20));await commit([write('files',key,{mime:file.type,name:file.name,size:file.size,chunks:writes.length})]);return key;}catch(e){try{await removeFile(key)}catch{}throw e;}}
 async function resetAccount(confirmation:string){if(confirmation!=='APAGAR TUDO')throw Error('Digite APAGAR TUDO para confirmar a exclusão.');await token();if(resetting)throw Error('A exclusão já está em andamento.');resetting=true;let count=0;try{const remove=async(docs:any[])=>{for(let i=0;i<docs.length;i+=400){const batch=docs.slice(i,i+400);await commit(batch.map(d=>({delete:d.name})));count+=batch.length;}};for(const file of await readCollection('files')){const key=file.name.split('/').at(-1)!;await remove(await readCollection('files/'+encodeURIComponent(key)+'/chunks'));await remove([file]);}for(const name of ['records','versions','history'])await remove(await readCollection(name));return {reset:true,deletedDocuments:count,records:[]};}catch(e){throw Error('A exclusão foi interrompida. Parte dos dados pode ter sido apagada. Tente novamente para finalizar. '+(e as Error).message);}finally{resetting=false}}
 async function api(input:RequestInfo|URL,init?:RequestInit){const url=new URL(typeof input==='string'?input:input instanceof URL?input.href:input.url,location.origin),method=init?.method||'GET';if(url.origin!==location.origin||!url.pathname.startsWith('/api/'))return nativeFetch(input,init);try{
 if(url.pathname==='/api/timeline-update'){if(method!=='POST')return Response.json({error:'Use POST.'},{status:405});await token();if(session.uid!==config.ownerUid)throw Error('Esta atualização pertence à conta responsável pelo estúdio.');const body=JSON.parse(String(init?.body)),rows=await records(),next=applyTimelineUpdate(body,rows);return Response.json(next?await saveInput(next):{reused:true,records:rows.map(strip)});}
 if(url.pathname==='/api/reset'){if(method!=='POST')return Response.json({error:'Use a confirmação para excluir seus dados.'},{status:405});return Response.json(await resetAccount(JSON.parse(String(init?.body)).confirmation));}
 if(resetting&&method!=='GET')throw Error('Aguarde a conclusão da exclusão antes de salvar.');
 if(url.pathname==='/api/records'&&method==='POST')return Response.json(await saveInput(JSON.parse(String(init?.body))));
 if(url.pathname==='/api/records')return Response.json({records:(await records()).map(strip)});
 if(url.pathname==='/api/reconcile'){let rows=await records();for(const input of rows.filter(r=>!r.deleted&&!r.archived).sort((a,b)=>({clients:0,projects:1,budgets:2,tasks:3}[a.kind as string]??4)-({clients:0,projects:1,budgets:2,tasks:3}[b.kind as string]??4))){if(input.client&&!rows.some(r=>r.id===input.client&&!r.deleted))continue;const current=rows.find(r=>r.id===input.id)!;const flow=prepareStudioFlow(current,rows,today());if(flow.related.length||JSON.stringify(strip(flow.record))!==JSON.stringify(strip(current))){await save(flow.record,flow.related,rows);rows=await records();}}return Response.json({records:rows.map(strip)});}
 if(url.pathname==='/api/integrate'){const body=JSON.parse(String(init?.body)),rows=await records(),budget=rows.find(r=>r.id===body.budgetId);if(!budget)throw Error('Orçamento não encontrado.');if(budget.integration?.completed)return Response.json({reused:true});return Response.json(await saveInput({...budget,status:'Aprovado'}));}
 if(url.pathname==='/api/installments'){const body=JSON.parse(String(init?.body)),rows=await records(),source=rows.find(r=>r.id===body.id);if(!source||source.kind!=='finance'||source.deleted||source.status==='Pago')throw Error('Selecione uma parcela pendente.');if(source.installmentsCreated)return Response.json({reused:true});const plan=installmentPlan(Number(source.value),Number(source.installments),source.date),all=plan.map((p,i)=>({...source,...p,id:i?source.id+'-parcela-'+(i+1):source.id,revision:i?0:source.revision,title:source.title+' · '+(i+1)+'/'+plan.length,installment:i+1,installmentsCreated:true,totalOriginal:source.value}));return Response.json(await save(all[0],all.slice(1),rows));}
 if(['/api/history','/api/versions'].includes(url.pathname)){const type=url.pathname.split('/').at(-1)!,id=url.searchParams.get('id'),list=(await readCollection(type)).map(decode).filter(r=>r.recordId===id||type==='history'&&(r.client===id||r.project===id)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,100).map(strip);return Response.json({[type]:list});}
 if(url.pathname==='/api/fonts'&&method==='POST'){const file=(init?.body as FormData).get('file');if(!(file instanceof File)||file.size>2*1024*1024)throw Error('Use fonte de até 2 MB.');const format=fontFormat(new Uint8Array(await file.arrayBuffer()));if(!format)throw Error('Fonte inválida.');return Response.json({url:'/api/fonts?key='+await uploadFile(file),format});}
 if(url.pathname==='/api/fonts')return new Response(await readFile(url.searchParams.get('key')||''));
 if(url.pathname==='/api/assets'&&method==='POST'){const file=(init?.body as FormData).get('file');if(!(file instanceof File)||!['image/png','image/jpeg'].includes(file.type)||file.size>4*1024*1024)throw Error('Use PNG ou JPEG com até 4 MB.');const bytes=new Uint8Array(await file.arrayBuffer());if(file.type==='image/png'&&!(bytes[0]===137&&bytes[1]===80&&bytes[2]===78)||file.type==='image/jpeg'&&!(bytes[0]===255&&bytes[1]===216))throw Error('Imagem inválida.');return Response.json({url:'/api/assets?key='+await uploadFile(file)});}
 if(url.pathname==='/api/assets')return new Response(await readFile(url.searchParams.get('key')||''));
 if(url.pathname==='/api/attachments'&&method==='POST'){const form=init?.body as FormData,file=form.get('file'),id=String(form.get('record')),signed=form.get('signed')==='true';const rows=await records(),record=rows.find(r=>r.id===id);if(!record||record.deleted||!['clients','contracts'].includes(record.kind))throw Error('Salve a ficha do cliente ou contrato primeiro.');if((record.attachments||[]).length>=30)throw Error('Use até 30 anexos.');if(!(file instanceof File)||file.type!=='application/pdf'||file.size>15*1024*1024)throw Error('Use PDF de até 15 MB.');const bytes=new Uint8Array(await file.arrayBuffer());if(new TextDecoder().decode(bytes.slice(0,5))!=='%PDF-')throw Error('PDF inválido.');const key=await uploadFile(file),attachment={id:crypto.randomUUID(),key,name:file.name,size:file.size,role:signed?'Contrato assinado':'Documento',uploadedAt:new Date().toISOString()},next={...record,attachments:[...(record.attachments||[]),attachment],...(signed&&record.kind==='contracts'?{status:'Assinado'}:{})};try{const related:Entry[]=signed&&record.kind==='clients'?[{id:'signed-'+attachment.id,kind:'contracts',title:'Contrato assinado · '+record.title,client:record.id,status:'Assinado',date:today(),attachments:[attachment]}]:[];return Response.json(await save(next,related,rows));}catch(e){try{await removeFile(key)}catch{}throw e;}}
 if(url.pathname==='/api/attachments'){const key=url.searchParams.get('key')||'',record=(await records()).find(r=>r.id===url.searchParams.get('record')&&!r.deleted);if(!record?.attachments?.some((a:any)=>a.key===key))throw Error('Anexo não encontrado.');return new Response(await readFile(key),{headers:{'Content-Type':'application/pdf'}});}
 return Response.json({error:'Operação não disponível.'},{status:404});
 }catch(e){return Response.json({error:(e as Error).message},{status:/mudou/.test((e as Error).message)?409:400});}}
 return {api,acceptGoogleSession:async(idToken:string,refreshToken:string)=>{const response=await nativeFetch(`https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${encodeURIComponent(config.apiKey)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idToken})});const data:any=await response.json();const user=data.users?.[0];if(!response.ok||!user?.localId||(!config.multiUserEnabled&&user.localId!==config.ownerUid))throw Error('Esta conta não é a responsável pelo estúdio.');session={uid:user.localId,email:user.email||'',idToken,refreshToken,expiresAt:Date.now()+3500000};remember();},hasSession:()=>!!session&&(config.multiUserEnabled||session.uid===config.ownerUid),account:()=>session?{uid:session.uid,email:session.email||'',owner:session.uid===config.ownerUid}:null,signOut:()=>{session=null;sessionStorage.removeItem(storageKey)},signIn:async(email:string,password:string)=>{const response=await nativeFetch(`https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=${encodeURIComponent(config.apiKey)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,returnSecureToken:true})}),data:any=await response.json();if(!response.ok)throw Error('Não foi possível entrar. Confira seu e-mail, senha e a configuração do Firebase.');if(!config.multiUserEnabled&&data.localId!==config.ownerUid)throw Error('Esta conta não é a responsável pelo estúdio.');session={uid:data.localId,email:data.email||email,idToken:data.idToken,refreshToken:data.refreshToken,expiresAt:Date.now()+Number(data.expiresIn)*1000};remember();}};
}
