import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import Studio from '../app/page';
import {createFirebaseBridge} from './firebase-bridge';
import {activateStudioAccount} from '../lib/account-storage';
import {newStudioSettings} from '../lib/studio-account';
import '../app/globals.css';
const nativeFetch=window.fetch.bind(window);
let bridge:ReturnType<typeof createFirebaseBridge>|null=null;
let auth:any,sdk:any;
function App(){
 const [ready,setReady]=useState(false),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[onboarding,setOnboarding]=useState(false),[name,setName]=useState(''),[studioName,setStudioName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[mode,setMode]=useState('login'),[passwordEnabled,setPasswordEnabled]=useState(false),[signedIn,setSignedIn]=useState(false);
 async function enter(){const account=bridge!.account();if(!account)throw Error('Entre novamente para continuar.');setSignedIn(true);activateStudioAccount(account);const response=await bridge!.api('/api/records'),body:any=await response.json();if(!response.ok)throw Error(account.owner?body.error:'O cadastro de novos estúdios ainda está em preparação. Seu acesso não foi liberado.');const settings=body.records.find((r:any)=>r.kind==='settings');if(account.owner||settings){setReady(true);document.title=(settings?.title||'Meu Estúdio')+' · Meu Estúdio';}else{setName('');setStudioName('');setOnboarding(true);}}
 useEffect(()=>{(async()=>{const response=await nativeFetch('/firebase-config.json');if(!response.ok)throw Error('Não foi possível carregar a configuração.');const config:any=await response.json();if(!config.apiKey||!config.authDomain||!config.projectId||!config.ownerUid)throw Error('Configure a conexão com o Firebase.');bridge=createFirebaseBridge(config,nativeFetch);window.fetch=bridge.api;(window as any).__nunesGithub=true;
 // Password registration is activated only after migration to the commercial host.
 setPasswordEnabled(config.passwordAuthEnabled===true&&!location.hostname.endsWith('.github.io'));
 const appUrl='https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js',authUrl='https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js';const [apps,authentication]=await Promise.all([import(/* @vite-ignore */ appUrl),import(/* @vite-ignore */ authUrl)]);sdk=authentication;auth=sdk.getAuth(apps.initializeApp(config));await sdk.setPersistence(auth,sdk.inMemoryPersistence);setLoaded(true);if(bridge.hasSession())await enter();})().catch(e=>setError(e.message));},[]);
 const authError=(e:any)=>e.code==='auth/popup-blocked'?'Permita a janela de login no navegador e tente novamente.':e.code==='auth/popup-closed-by-user'?'A janela foi fechada. Clique para entrar novamente.':e.code==='auth/unauthorized-domain'?'Este endereço ainda não está habilitado para login.':e.code==='auth/email-already-in-use'?'Este e-mail já tem uma conta. Entre com ela.':e.code==='auth/operation-not-allowed'?'Esta forma de acesso ainda não está disponível. Use o Google.':e.code==='auth/invalid-credential'?'Confira seu e-mail e senha.':e.code==='auth/weak-password'?'Escolha uma senha com pelo menos 8 caracteres.':e.message||'Não foi possível entrar.';
 async function loginGoogle(){setBusy(true);setError('');try{const provider=new sdk.GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});const result=await sdk.signInWithPopup(auth,provider);try{await bridge!.acceptGoogleSession(await result.user.getIdToken(),result.user.refreshToken);}finally{await sdk.signOut(auth)}await enter();}catch(e:any){setError(authError(e))}finally{setBusy(false)}}
 async function loginEmail(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{if(mode==='reset'){await sdk.sendPasswordResetEmail(auth,email);setError('Se houver uma conta para este e-mail, você receberá as instruções de recuperação.');return;}const result=mode==='signup'?await sdk.createUserWithEmailAndPassword(auth,email,password):await sdk.signInWithEmailAndPassword(auth,email,password);try{if(!result.user.emailVerified){await sdk.sendEmailVerification(result.user);throw Error('Confira seu e-mail para confirmar a conta. Depois, entre novamente.')}await bridge!.acceptGoogleSession(await result.user.getIdToken(),result.user.refreshToken)}finally{await sdk.signOut(auth)}setPassword('');await enter();}catch(e:any){setError(authError(e))}finally{setBusy(false)}}
 async function complete(e:React.FormEvent){e.preventDefault();if(!name.trim()||!studioName.trim())return;setBusy(true);setError('');try{const response=await bridge!.api('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(newStudioSettings(name,studioName,bridge!.account()!.email))}),body:any=await response.json();if(!response.ok)throw Error(body.error);setOnboarding(false);document.title=studioName+' · Meu Estúdio';setReady(true);}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 function signOut(){bridge?.signOut();window.location.hash='';window.location.reload()}
 if(ready)return <><button className="github-signout button" onClick={signOut}>Sair da conta</button><Studio/></>;
 return <main className="studio-login"><aside className="login-story"><div><p className="login-brand">meu estúdio<span>.</span></p><h1>seu estúdio,<br/><em>mais leve</em></h1><p className="login-description">Clientes, orçamentos, prazos, contratos e pagamentos num lugar só, no celular e no computador.</p></div></aside><section className="login-access"><div className="login-access-inner"><p className="eyebrow">— área restrita</p><h2>bem-vinda <em>de volta</em></h2>{onboarding?<form onSubmit={complete}><label className="field"><span>Como você quer ser chamada?</span><input autoComplete="given-name" required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>Qual é o nome do seu estúdio?</span><input required maxLength={150} value={studioName} onChange={e=>setStudioName(e.target.value)}/></label><button className="button primary" disabled={busy}>Criar meu estúdio</button></form>:<><p className="login-account-note">Acesse sua conta para continuar.</p>{passwordEnabled&&<form onSubmit={loginEmail}><label className="field"><span>e-mail</span><input type="email" autoComplete="email" placeholder="nome@gmail.com" required value={email} onChange={e=>setEmail(e.target.value)}/></label>{mode!=='reset'&&<label className="field"><span>senha</span><input type="password" autoComplete={mode==='signup'?'new-password':'current-password'} minLength={mode==='signup'?8:undefined} required value={password} onChange={e=>setPassword(e.target.value)}/></label>}<button className="button primary" disabled={busy}>{mode==='reset'?'recuperar senha':'entrar ›'}</button><button type="button" className="text-button" onClick={()=>{setError('');setMode(mode==='reset'?'login':'reset')}}>{mode==='reset'?'voltar ao login':'esqueci minha senha'}</button></form>}<button className="button primary login-google" disabled={!loaded||busy} onClick={loginGoogle}><span className="google-mark">G</span>{busy?'Entrando…':loaded?'entrar com Google':'Carregando acesso…'}<span>›</span></button><p className="login-session-note">Seu espaço, suas informações e seus projetos, sempre que precisar.</p><p className="login-personal-note">Uma gestão mais leve para o seu estúdio.</p></>}{error&&<p className="login-error" role="alert">{error}</p>}{signedIn&&!ready&&<button className="text-button" onClick={signOut}>Sair e usar outra conta</button>}</div></section></main>;

}
createRoot(document.getElementById('root')!).render(<App/>);
